### ISSUE TITLE
Clubs branding and naming

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#100]
### We need to discuss:
- what the website name will be (eg Mozilla Clubs, Clubs _followed by Mozilla in small text_...)
- how individual clubs will be named (eg Mozilla Clubs Islamabad, Clubs Islamabad _followed by Mozilla in small text_, affiliate name...)
- what our website logo/wordmark will look like 
- what individual clubs logos/wordmarks will look like

I believe @LucyeoH and @supnah have discussed this a little? Could you please share any progress or research you have so we're all on the same page?

### Here's a random sampling of existing names and the logos they've made for themselves: 
Mozilla Campus Clubs Philippines
Mozilla Campus Clubs, Bangladesh
NSU Mozilla Club
Mozilla Club Coherent
Mozilla Campus Club at DIU
Mozilla Tirupati
ABJ Mozilla Digital Education Club 
Mozilla Club Islamabad 
Abdelrahman Samy Ahmed Mohamed Tolis 
Mozilla Club Munnar 
Active Minds
Akili Dada

![title](https://cloud.githubusercontent.com/assets/1068783/24313505/48440fd0-109a-11e7-9ae9-1c80902a4042.png)

![4pueqgvj](https://cloud.githubusercontent.com/assets/1068783/24313490/35f44a7a-109a-11e7-9088-1d3db01f7239.jpg)
![87rumyfk](https://cloud.githubusercontent.com/assets/1068783/24313488/35f2a396-109a-11e7-9cf7-8fbfd30dce08.jpg)
![23620540](https://cloud.githubusercontent.com/assets/1068783/24313489/35f37fc8-109a-11e7-9602-661f4b6760ea.png)
![nbtpytvx](https://cloud.githubusercontent.com/assets/1068783/24313498/3ee9d050-109a-11e7-99af-1c5b013524b7.jpg)
<img width="638" alt="screen shot 2017-03-24 at 1 54 17 pm" src="https://cloud.githubusercontent.com/assets/1068783/24313501/431cf166-109a-11e7-95ad-3a78bca17bdb.png">
<img width="595" alt="screen shot 2017-03-24 at 1 54 33 pm" src="https://cloud.githubusercontent.com/assets/1068783/24313503/4337fbaa-109a-11e7-9a18-a680d8d6f329.png">
<img width="601" alt="screen shot 2017-03-24 at 1 54 56 pm" src="https://cloud.githubusercontent.com/assets/1068783/24313502/43351250-109a-11e7-87a6-7bfb132788a6.png">
<img width="490" alt="screen shot 2017-03-24 at 1 58 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/24313504/4522887c-109a-11e7-8def-e2644e7c6786.png">

**Comment by LucyeoH** [comment]
Hey @kristinashu 

If each program has their own landing page - how does this affect this? Is this what will appear at the top of shared pages? 

For Student Clubs - what about an optional "powered by Mozilla" workmark? Also can we have an option for if they don't have Mozilla in their name at all, for example "Open Source Technology Club - Occidental College"  or "Open Michigan - University of Michigan".

**Comment by a-kilroy** [comment]
These are great questions. @kristinashu and @m-branson (if you can join) maybe we can use our standup today to go through some ideas I have? I think pomax and Alan have a conflict so won't be joining.

**Comment by kristinashu** [comment]
For now, I'd love to start with just one Clubs logo (for both Open Source Clubs and Web Literacy Clubs) and then if the need arises for a unique one, then we can make it. Even with different landing pages, it would be ideal to keep a consistent logo (and reflect the differences in the copy and content - as in this [doc](https://docs.google.com/a/mozilla.com/presentation/d/1Ou6CFoDKHzbwAYKKtjADpoFp6zftEVklzQeWJq_Uh3k/edit?usp=sharing)).

For individual Clubs, we won't force anyone to make a logo (it just seems like it's something they like to have) but it would be great to provide them with a resource to make a nice logo that aligns with our look and feel. Possibly an improved version of what [we currently offer now](https://d157rqmxrxj6ey.cloudfront.net/mozillalearning/17695/). We could provide guidance on on using our new type face and logo proportions but up the them what they want to call it and they could customize it in other ways (image, color...). Up to them if the want to include "mozilla" or not.

**Comment by a-kilroy** [comment]
@kristinashu Agreed. I think this makes sense for the first iterations. There is a lot of ways we could handle this so we'll want to give it proper attention post the more critical functionality (like the ability to have a club page at all :P)
