### ISSUE TITLE
User journeys diagram

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#106]
Based on sketch from @a-kilroy, we will collaborate with others to build this out in more detail.

<img width="507" alt="screen shot 2017-03-30 at 2 03 29 pm" src="https://cloud.githubusercontent.com/assets/1068783/24526613/983ee79a-1553-11e7-83df-64a763d5902f.png">

**Comment by a-kilroy** [comment]
Better version here for posterity 
![osclubsjourney](https://cloud.githubusercontent.com/assets/20068088/24777753/adb2d93c-1adb-11e7-8ff5-3c7c42f7a328.jpeg)

**Comment by hmitsch** [comment]
For the record, earlier today this was put into electronic form and remixed with some of the information captured in @kristinashu's [Main Deck](https://docs.google.com/presentation/d/1V5nJbZxgJPnW3Ggz5Jz1iid22kOlo-9R6RGHZO1LGJo/edit). The slide was added to section _Clubs+Advocacy User Flows_.

For accessibility, I paste an image of it here.

<img width="988" alt="image" src="https://cloud.githubusercontent.com/assets/869692/24931953/a2d6b42e-1f0f-11e7-8a62-7a07db2980c5.png">

**Comment by a-kilroy** [comment]
@hmitsch Flipping it doesn't quite work right... there are some inaccuracies here but if you want it like this I think we can make some changes to address the issues.
