### ISSUE TITLE
Sprint Goal 1 - 02/07-02/17 2017

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#11]
Goals:
- Getting up and running with ZenHub 
*This will be a bit messy for a sprint or two as we work out how to literally do work together

- Flush out initial steps for the first items in Berlin Work Week project map
    - Comprehensive IA design
    - Clubs Data Model
    - Event Platform Research - meetup/facebook API
    - Clubs/Campus Club Brand and Messaging Alignment
    - Github Partnership
    - CMS Research

Not in first steps on product roadmap but implied by work is selecting a CMS

**Comment by hmitsch** [comment]
@a-kilroy I fixed the markdown syntax. Hope that was okay.
