### ISSUE TITLE
Provide Passwordless and Staff LDAP login to CoSS

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#120]
@johngian @akatsoulas Can you add a task list to this?

**Comment by johngian** [comment]
- [ ] Merge #117 
- [ ] Coordinate with infosec to get auth0 credentials for our dev deployment
- [ ] Configure dev to use auth0 credentials

**Comment by johngian** [comment]
* Requested auth0 credentials via service now

**Comment by a-kilroy** [comment]
@akatsoulas This seems outdated. Any objections with me closing?

**Comment by akatsoulas** [comment]
Sounds good to me.
