### ISSUE TITLE
Alignment Details

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#121]
Create a document that outlines both areas/processes where we believe there is flexibility to more closely align and areas where we see contrasts/constraints especially as it relates to affecting User Experience.

**Comment by a-kilroy** [comment]
Here are the docs from [Kristina](https://docs.google.com/document/d/1p_iSvHPjTncRbvIDvw7QaZaU1UJwB6OUHW2Ur51Uoeo/edit#heading=h.s1qg377mozi0) @kristinashu [Amira/Julia](https://docs.google.com/document/d/1lWkljGZ6Cl1LQCWkArTcvJry3YBM3C8dtp8iqXigMdA/edit#heading=h.1dxiefih07fy) @amirad @jvallera and from [Lucy/Christos ](https://docs.google.com/document/d/1MjnwezNKG_FZVeGXRhnCRnRlsGTamBLzHlTSDMC79vU/edit#heading=h.oyeurjpmt59)@LucyeoH @bacharakis 
Take all of these with a 'grain of salt'. I've spoken to all of you and I think there are lots of things that are nuanced here that Kristina and I will try to express. You'll all have the opportunity to give feedback on this doc before we figure out how we take this to the higher ups to make decisions.

**Comment by amirad** [comment]
Thanks @a-kilroy - these are helpful to read!
