### ISSUE TITLE
Sign Up Process Ticket

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#124]
@johngian @akatsoulas Can you detail the steps here that you'd need to do a Club Registration sign up flow. https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087690_Home

**Comment by akatsoulas** [comment]
@a-kilroy I am gathering the requirements for this and I will come back with a task list (and probably more issues) asap.

**Comment by akatsoulas** [comment]
Closing this in favor of #156 and #157
