### ISSUE TITLE
Layout Implementation 

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#130]
Layouts for Implementation:
* [x] P1) Single column https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087702
* [ ] P2) Three column https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087705
* [ ] P3) Single column hero area with two column body https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087731

**Comment by comzeradd** [comment]
Closing this in favor of #168 and #171
