### ISSUE TITLE
Apply visual design to the Club Member flow

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#147]
**"As a user I want to join an Open Source club."**

Apply visual design to the Club Member flow through iteration of the wireframes. Use initial landing page design and user journeys as reference.

**Comment by m-branson** [comment]
Began 'become a club member' flow: built 'Find A Club' UI for all and open source filtering. Club specific content is still being fleshed out (club names/descriptions). Next step for this flow will be to add a club page design and 'join' UI. [Prototype here.](https://invis.io/S8BTUSWQN#/235067665_Clubs_Landing)

**Comment by m-branson** [comment]
Populated an 'existing' open source club page. @a-kilroy take a look below. Didn't get to 'resources' today, but will add that tomorrow (btw, any good ideas for what a club resource would be?). 

For the event list, does it feel like we're capturing all of the pertinent info here? I'm thinking that we'll push users to a more detailed event page with the RSVP button...wonder if it should be a 'more info' button instead then? Also, thinking I'll add a 'See All Events' CTA to the bottom of the list as well. Overall thoughts?

![existing entity detail page - os - logged out 1x](https://user-images.githubusercontent.com/18686986/26956138-7a41909a-4c70-11e7-90e8-ac870e8633be.jpg)

**Comment by a-kilroy** [comment]
Find examples of resources: 
https://campus.mozilla.community/resources/
https://learning.mozilla.org/en-US/activities
Often links to things. Could surfaces these to the users by resource type (curriculum, form templates, trainings, etc) or popularity or something

**Comment by m-branson** [comment]
Thanks for the example @a-kilroy ... I did a mix of club specific and Mozilla generic. They are currently just simplified text links. Keeping these simple to start makes the most sense from a templating sense, once we have a clearer idea of what these resources will look like I'd like to tailor the categorization further.

Here's the updating existing club page based on feedback from our team stand. I'll get this linked to the New Club Member Flow next week.

![existing entity detail page - os new - logged out](https://user-images.githubusercontent.com/18686986/26998958-c5fa1d5e-4d42-11e7-9633-0aa5c1363349.jpg)

**Comment by m-branson** [comment]
The [prototype](https://invis.io/QNC0SQD24) has been updated and users can now join a club! From the '[VR at San Francisco University](https://projects.invisionapp.com/d/main#/console/11220819/237277882/preview)' club detail page, users can click 'Join This Club' and follow the prompts to log in / sign up + join.

@a-kilroy want to take a spin through and let me know your thoughts? Would like to fine tune this flow before adding it to the other club page ([UC Berkeley HCI](https://projects.invisionapp.com/d/main#/console/11220819/238515713/preview)).

**Comment by m-branson** [comment]
Applied the new member join flow to the [UC Berkeley HCI](https://projects.invisionapp.com/d/main#/console/11220819/238515713/preview) club page. Click 'Join this club' to walk through, click 'leave this club' at the end to start over. 👍

**Comment by m-branson** [comment]
Closing, will review and outline needed iterations in #188.
