### ISSUE TITLE
Create the template for the SignUp process.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#156]
Create a basic template to register a club. The fields in the template should follow this mock-up [0]. As for UI, we can follow for now the paradigm from the landing page and we can change it when the final version is ready.

[0] https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087730

**Comment by comzeradd** [comment]
[PR](https://github.com/mozilla/coss/pull/164) opened

**Comment by akatsoulas** [comment]
This is already merged. Any issues that may arise will be tackled in different issues.
