### ISSUE TITLE
Visual Design: About Page

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#160]
Design an 'About' page template based on this Campus Clubs [content](https://campus.mozilla.community/about/).

**Comment by m-branson** [comment]
The initial version of the About page design is done and synced to the [prototype](https://projects.invisionapp.com/share/QNC0SQD24#/screens/239963062).

I've taken some liberties with the copy (condensing and renaming to Open Source from Campus) and created a page length that is a bit more digestible on initial scroll. The goal of this approach would be that users are encouraged to explore the sections they are most interested in.

**Comment by m-branson** [comment]
Captured feedback from review w/@a-kilroy that I'll implement today:

- [ ] Consider a way to bring attention to content on the lower portion of the page, specifically the club roles section. Will investigate use of an in-page anchor nav that does not compete with the main navigation.
- [ ] Make club roles more of a focus than club history. Currently hierarchy is with history due to color treatment.

**Comment by m-branson** [comment]
The [about page](https://projects.invisionapp.com/share/UYC9ST17F#/screens/240171460) has been updated based on this morning's review. Moving this issue to review. 👍

**Comment by a-kilroy** [comment]
Looks great! Really love the structure. I think it's super flexible.

**Comment by m-branson** [comment]
Awesome, thanks @a-kilroy! Closing this one out, further iterations will be tracked by future issues.
