### ISSUE TITLE
Visual Design: Find A Club

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#163]
This has been started via #147, requires iteration and refinement:

- [x] Utilize long, medium and short group names
- [x] Utilize groups with and without an image
- [x] Give some coordinator avatars photos
- [x] Maintain a max-height/max-width for group cards
- [x] Truncate description text

**Comment by m-branson** [comment]
Updated task to reflect global, top-level navigation changes from Find A Club > Find A Group.

This page will still allow users to 'filter' by Open Source Clubs, resulting in visual cards that highlight both an existing club and a new club. As part of the New Club Member flow (#147) users will be able to view both (and join the new club).

cc @a-kilroy

**Comment by m-branson** [comment]
Got started with some edits, specifically adding some contextual examples and changing 'club' verbiage to 'group' verbiage. Photos & name/description lengths will be updated on Monday.

![updated category search 1x](https://user-images.githubusercontent.com/18686986/26992327-00428c24-4d13-11e7-8a63-f364efc24d65.jpg)

**Comment by m-branson** [comment]
The [Find A Group](https://projects.invisionapp.com/d/main#/console/11220819/237277899/preview) page now highlights group cards that are more diverse in template structure while maintaining a uniform height/width. This includes: varying title lengths, varying description truncation, image vs. no image and use of different category icon/color labeling.

Moving this to review, @a-kilroy let me know your thoughts here as well. Thanks!

**Comment by a-kilroy** [comment]
Looks great. I expect this to be a page that will evolve greatly over time
but for it's immediate job of showing discovery -> specialized is achieved.

**Comment by m-branson** [comment]
Thanks! And agreed, I see a lot of iteration in the future for this page. 🔮 

Moving this ticket to closed, future iterations will be tracked in new issues.
