### ISSUE TITLE
Migrate Prototype to Mozilla InVision

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#169]
I'll be moving the CoSS prototype to an InVision account that utilizes a mozilla email. This will enable sharing the project with others who have InVision accounts with their mozilla email. 

In order for engineers to [inspect](https://www.invisionapp.com/feature/inspect?utm_source=google&utm_medium=paid_search&utm_campaign=G_NAM_Search_Brand_EM&utm_content=InVision_Inspect_EM&utm_term=invision%20inspect_e&_bk=invision%20inspect&_bt=188134871266&_bm=e&_bn=g&gclid=Cj0KEQjwmcTJBRCYirao6oWPyMsBEiQA9hQPbiUYk7_fNjeOVUXrJTvCFCCqVhoQTmV7-QQmh-HViCQaAnZ18P8HAQ) the project, they'll need to log in to InVision and have access to the project.

@comzeradd @akatsoulas you can sign up for a free InVision account via your Mozilla email, I can then share the project with you 👍

**Comment by akatsoulas** [comment]
@m-branson done!

**Comment by comzeradd** [comment]
@m-branson done

**Comment by m-branson** [comment]
[Prototype](https://invis.io/QNC0SQD24) ownership has been moved over to my mozilla email and invites were sent to your inboxes @akatsoulas @comzeradd @a-kilroy. Let me know if you don't see them.

@a-kilroy the only thing left on this issue is to add all of us to the mozilla invision account, assigning this one to you for that.

**Comment by m-branson** [comment]
Closing this issue, prototype is owned by mbranson@mozilla.com. Will be merged to a Mozilla InVision account after all hands.
