### ISSUE TITLE
Event Platform Research

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#19]

**Comment by alanmoo** [comment]
Should we be evaluating any other platforms at this time? I know there was talk of EventBrite for larger events. Is that out of scope for what we're working on right now?

**Comment by a-kilroy** [comment]
@alanmoo You can look at their API if you want. My understanding is that people use it for functionality not for the "meet people where they are" which was the line of thought behind evaluation of Facebook and Meetup. Does this answer your question?

**Comment by kristinashu** [comment]
@a-kilroy do you have a doc started for this?

**Comment by kristinashu** [comment]
cc @simonwex

**Comment by a-kilroy** [comment]
Closing this. Will re open if we decide to not move forward with Splash.
