### ISSUE TITLE
Event Detail Sync (SplashThat Version)

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#190]
- [x] Update baseline SplashThat event detail template to match the baseline styles of the Visual Prototype.
- [x] Populate an event detail page with content from a prototype event.
- [x] Link prototype to the event detail page (new tab).

**Comment by m-branson** [comment]
The Splash event page has been updated stylistically to better mirror the prototype experience. That said, here are some issues I've run into:
- I'm unable to alter the size of the mozilla logo (even if I resized the logo and reuploaded). I attempted to replace the moz logo with the clubs logo, it ended up HUGE due to specific template size values. I made the nav invisible to get a gut check on it's necessity. I don't feel that it does much to the page usability wise (esp as it isn't sticky) and would like to avoid branding this event a 'Mozilla' event. Perhaps I'm overthinking? @a-kilroy feel free to make it visible again if you think it adds to your preso.
- The 'Club Members' background waterfall gif appears to be hardcoded? I've inspected it and am unable to affect the specific div within the CMS tools. Would LOVE to turn this off and be able to utilize just the background color. @a-kilroy worthwhile to reach out to Splash and get some info around that?
- Similar to the waterfall gif, I can't figure out where the background color is applied to the Speaker blocks. I've spent far too much time clicking around attempting to edit it... @a-kilroy I'm guessing these are some hard coded attributes.
- Overall good to know that we'll be able to place these types of limitations on our templates (e.g. hardcoding certain options) though not helpful at this point for customizing.

You can now link to the event page from the [prototype UC Berkeley club page](https://projects.invisionapp.com/share/QNC0SQD24#/screens/238515713).

Moving this issue to review, will talk through further in tomorrow's team stand.

**Comment by m-branson** [comment]
With updated 'design pro' access I was able to remove the waterfall gif and adjust colors for  backgrounds + social icons. For initial prototype demo purposes this should do the trick. Closing this one out.

**Comment by a-kilroy** [comment]
This looks great. For ease, can I request that we move the linked event to the first event slot in the entity page list?

**Comment by m-branson** [comment]
Done. Also changed the date across the protoype + event demo to keep lists ordered by date. ;)
