### ISSUE TITLE
Clubs/Campus Club Brand and Messaging Direction

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#20]
Meeting with Lucy, Christos, Amira, and Julia. We decided to work towards a singular brand with a personalized user experience for the sub brands that allows for cross pollination. Naming/visuals will be on hold until the report from the Campus Clubs consultant comes at the end of Feb.

**Comment by kristinashu** [comment]
Please keep me in the loop on any brand progress!

**Comment by a-kilroy** [comment]
I'm closing this ticket. Brand direction at a meta level was chosen. With research from @LucyeoH we'll be able to work on visuals/words for the branding and can open new tickets for that work.
