### ISSUE TITLE
Document local installation procedure.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#208]
The goal is to have up to date documentation for local installation and development for Mezzanine or its replacement.

**Comment by akatsoulas** [comment]
This should be done in `read the docs`

**Comment by akatsoulas** [comment]
This is blocked by issue #212. We won't be able to properly document CoSS until we reach a decision regarding CMS selection.

**Comment by comzeradd** [comment]
Fixed at bc8a0fbeca383a057f7478d4f24e2c4fc572386f
