### ISSUE TITLE
UI Style Guide v1

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#214]
Based on the current OS Clubs prototype, I will generate a basic UI style guide to provide initial guidance in the front-end execution of CoSS templates and components.

This style guide will include:
- typography/font use
- color palette
- iconography/logo use
- basic templating for forms and buttons

**Comment by m-branson** [comment]
Further investigation into InVision's 'inspect' tool highlights that a UI style guide work effort is not needed. Within the prototype engineers are able to gather all UI specs needed to build a CSS style guide and fine tune for responsiveness. (screenshot attached) As this prototype is browser based, it's more accessible than a Sketch style guide. Also, any needed assets (iconography, logos, fonts) have been made available in this [project folder](https://drive.google.com/open?id=0B0vmiicLLrGuVkNxMjVSbjZmYms).

![screenshot-2017-7-28 coss clubs inspect mode - invision](https://user-images.githubusercontent.com/18686986/28727834-1ef302dc-737b-11e7-8f97-b0d91aed5bc1.png)


@a-kilroy let's connect on Monday about this. I'd like to cut out duplicative process where possible and focus my efforts elsewhere (specifically Info Architecture and User Journeys for this project).

**Comment by m-branson** [comment]
@a-kilroy @akatsoulas @comzeradd -- I've been looking into ways that we can more readily host UI spec/guidelines. I've been able to export the spec from my Sketch file and into a file system which allows for hosting as a github page. I'm testing that instance [here](https://m-branson.github.io/coss-os-ui/index.html).

This is similar to InVision, but better as it keeps the spec and assets with the repo. It can more easily be updated and maintained this way as well. Plus engineers would be able to see when updates have been made.

What do you all think? Should we add a spec folder + enable github pages to get this set up?

**Comment by a-kilroy** [comment]
I'm in full support of this

**Comment by comzeradd** [comment]
We could create a gh-pages branch on the main repo to host this

**Comment by m-branson** [comment]
@comzeradd awesome, let me know when that's ready and I'll get this up for you all.

**Comment by m-branson** [comment]
Closing this, next steps live with #277.
