### ISSUE TITLE
Centralize in process event requirements gathering

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#22]
Lots of in process 'event' type work happening across Mozilla. First step is to gather and centralize.

**Comment by kristinashu** [comment]
I'm just going to add a few examples of where we are currently using events platforms, just to get the ball rolling. Then we can add requirements to them.
- [Mozilla Clubs](https://learning.mozilla.org/en-US/clubs) + [Campus Clubs](https://campus.mozilla.community/) events (currently nothing, FB, meetup, personal blogs/websites...) #3
- [Maker Party](http://makerparty.community/) (currently using Nation Builder, before that Blue State Digital)
- [MozFest]( https://mozillafestival.org/) (ticket sales using Tito)
- [Viewsource](https://viewsourceconf.org/) (ticket sales using Eventbrite)
- ...

cc @alanmoo @Pomax
