### ISSUE TITLE
CMS selection criteria list

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#23]
@alanmoo and I discussed having a list of 'things to consider when choosing a cms'. We can then quickly evaluate options against the list. Since there is no perfect option and we have a limited amount of time to make a decisions this seems like the best way to move forward. Feel free to suggest another approach. Definitely please add to this list with a comment. 

* internal Moz use of CMS and underlying language
* community use
* security
* maintenance
* set up time
* localization (frontend)
* localization (admin)

**Comment by a-kilroy** [comment]
@alanmoo and I discussed having a list of 'things to consider when choosing a cms'. We can then quickly evaluate options against the list. Since there is no perfect option and we have a limited amount of time to make a decisions this seems like the best way to move forward. Feel free to suggest another approach. Definitely please add to this list with a comment. 
-internal Moz use, community use, security, maintenance, set up time, localization (frontend), localization (admin)

**Comment by alanmoo** [comment]
* flexibility vs maintenance overhead
* how are pages/templates made
* REST API

**Comment by Pomax** [comment]
unplacking "use" a little:

- ease of content creation (form based vs. TinyMCEs vs. wysiwyg block composition, etc) 
- ease of content publication control
  - drafts
  - scheduled publications
  - scheduled expiry
  - active vs. archived content
- feeds
  - RSS
  - autoposting to other outlets (twitter, facebook, reddit, whatever)
- ease of user administration ("not everyone needs admin access" and thus how easily can a user be given specific rights without automatically getting rights they don't need)
- ease of custom extensions for functionality not found out of the box
   - rich ecosystem of well maintained plugins/extensions/etc
- good comments/feedback system, that's easily enabled/disabled on a per-piece (page, post, etc) basis.
- ease of interoperability with other services we run
- clean, stable, well versioned API

**Comment by alanmoo** [comment]
Good points, @Pomax. I'd like to see where some of these map to user stories though, I'm not sure where some of these fit in with our needs. (Other than the obvious "we could probably use this in the future")

**Comment by Pomax** [comment]
Agreed, although it will be important to make sure we balance the user stories: not every CMS has the same needs based on the users it needs to cater to, so it's worth noting that there is a real (if hopefully small) possibility that we still conclude with "different ones for different audiences".

**Comment by a-kilroy** [comment]
At the risk of 'thumbs upping' all your comments @Pomax I just want to say yes! It might still end with "different ones for different audiences" but making that choice early will allow us to plan for that, not forcing our first choice cms into our second project or our second choice cms into this project, or just building things in a way for them to be more reusable for both, etc.

**Comment by johngian** [comment]
To add to the list of requirements:

* Operations
  * Let's use something that we are experienced on how to run
  * Let's use something that supports a sane/modern deployment process

**Comment by Pomax** [comment]
@johngian for that first point, ops wanting a CMS they know, or a CMS implemented in a language/framework they know? Also, can you explain what "experienced" entails? E.g. if a CMS solution turns out to be great except it's a new cms/language that ops never worked with, would "doesn't take more than a few weeks to become experienced in" be acceptable for a new technology/stack? (mostly asking this to understand who has requests, and who has mandates)

**Comment by johngian** [comment]
@Pomax It was probably misleading the way that I put it. What I wanted to say is not to restrict to specific technologies that we have already used, rather use something that is prod ready and can be deployed to our current available systems stack (eg. docker, heroku, AWS, etc).

That said i am going to remove this from the initial comment since it's more of a preference than a requirement.

**Comment by flamingspaz** [comment]
"Well-supported" is probably the correct term there.

**Comment by kristinashu** [comment]
[CMS Requirements and Research Proposals](https://docs.google.com/a/mozilla.com/document/d/1_lRPvtfofs2qIruxJzmkLd7pWfZu8QJmFqFWQL4h14M/edit?usp=sharing) this is dated but parts of it could be relevant???

**Comment by Pomax** [comment]
definitely still relevant =)

**Comment by kristinashu** [comment]
I'm going to put everything listed above into spreadsheet and try to sort/group them. Then on the other axis we can add different CMS options and add notes. Does that sound like a good next step (aka useful)?

**Comment by Pomax** [comment]
@kristinashu yeah that would be quite useful. We can "tick the boxes" as it work while evaluating options (perhaps ranked 1-5 so we can do a SUM($col) but that pretty much bikeshedding, anything'll do).

Right now, it looks like Django-CMS ticks many of the requirements listed here.

**Comment by kristinashu** [comment]
Here's the [doc](https://docs.google.com/a/mozilla.com/spreadsheets/d/1F0n7P_uVN2Vjt8AQs2SxXUQPmqFnNImI8dvMJyRhASw/edit?usp=sharing), everyone please all add to it!

**Comment by a-kilroy** [comment]
This is awesome @kristinashu Lets sync when you are in. I appreciate you moving this forward while I was unexpectedly out.

**Comment by kristinashu** [comment]
Good to have you back @a-kilroy!

This might be getting to granular but I think it's worth noting that Julia has added a wish list in the [feedback on django ticket](https://github.com/mozilla/coss/issues/29#issuecomment-282062108).

**Comment by Pomax** [comment]
A few questions based on ticking the boxes in the new spreadsheet:

1. what is "active" vs. "archived" content?
2. what does "localization (admin panel)" mean? Localization of the actual entire backend UI?
3. what is "non-bespoke design"?

**Comment by kristinashu** [comment]
**1. what is "active" vs. "archived" content?**
I think you added this above? I interpreted it as being the ability to 'hide' something view without deleting it completely, in case you might want ti back later (ex. a resource guide)

**2. what does "localization (admin panel)" mean? Localization of the actual entire administration UI?**
I think so but @a-kilroy should confirm.

**3. what is "non-bespoke design"?**
This was from our original calypso research and probably not longer applies, I've deleted it.

**Comment by kristinashu** [comment]
List of requirements is done and in [this spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1mftbSX4P8sWQlS1_IOAdaU-7sFddrpy5vzp-CXEovF0/edit?usp=sharing) (second tab).

Please add to the sheet if you think of anything else.
