### ISSUE TITLE
Mozilla current CMS inventory

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#24]
Identify main community like sites and figure out what if any CMS they are using. Having a list of currently used CMSs will help us figure out if there is a choice that will aid in future scale.

**Comment by kristinashu** [comment]
I'm sure Arielle has more info on this and a better plan but here's a doc to get us started https://docs.google.com/a/mozilla.com/document/d/1OA1nIU4U2J_slcu81AOwws_cmFMjzwQPFxuqTeJ9Alg/edit?usp=sharing

@alanmoo @Pomax @akatsoulas @comzeradd please add any you know of

**Comment by kristinashu** [comment]
Sorry, @akatsoulas as well!

**Comment by kristinashu** [comment]
Sorry, I mean @johngian as well!

**Comment by kristinashu** [comment]
Here's next steps from our meeting with @a-kilroy and @alanmoo.

The doc above will be used for notes/interviews with staff who are currently using a CMS.

This [new spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1mftbSX4P8sWQlS1_IOAdaU-7sFddrpy5vzp-CXEovF0/edit?usp=sharing) will be used as an overview of all the key CMS sites at Mozilla.

I've set up some initial categories and sites, Arielle will add in MoCo sites that could eventual use CoSS tools, and at the same time engineers will determine which CMS those sites are using.

Goals for this are:
- know what staff are familiar with/like
- learn from their experiences
- make sure we can integrate with them

Does that sounds right @a-kilroy?

**Comment by a-kilroy** [comment]
Ha! I was like, 'has this spreadsheet has changed or am I imagining it?' This looks great. @kristinashu you'll take care of the MoFo ones right? I know you have a few listed but are there more? MLN? etc?

**Comment by kristinashu** [comment]
Those are the only one with a CMS (MLN doesn't have a CMS). Should I include _key_ sites even if they don't currently use a CMS?

**Comment by a-kilroy** [comment]
Yes I would. Especially if you think the staff would be interested in one in the future if there was an easy option.

**Comment by kristinashu** [comment]
Ok, I've added all the mofo properties. @Pomax @alanmoo could you please review?

**Comment by kristinashu** [comment]
Sites are listed in [this spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1mftbSX4P8sWQlS1_IOAdaU-7sFddrpy5vzp-CXEovF0/edit?usp=sharing).

General theme is that smaller static sites are primarily in Wordpress. Whereas as larger sites are done in Django (but mostly without a CMS).

I think this ticket is done but please reopen if you think more work is needed.
