### ISSUE TITLE
August 17 - Prepping for demo

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#256]
To do's:
- [x] merge @comzeradd  PR that has OS styled category landing page (aka the OS homepage) and a style Entity page. 
- [x] @a-kilroy will add 3 entities
- [x] @akatsoulas will work on the dynamic fields from the Entity displaying on the category landing page
- [ ] @akatsoulas and @comzeradd will identify items for clean up in the comments in this ticket. 
- [x] Footer anchored at the bottom of Entity page #257 
- [x] Entity page should include an image #260 
- [x] Create an Image gallery for the entity page in the back-end.

**Comment by akatsoulas** [comment]
Issue #257 is part of this effort.

**Comment by a-kilroy** [comment]
@akatsoulas added it

**Comment by comzeradd** [comment]
We can safely close this one :)
