### ISSUE TITLE
Name our repo and add readme

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#27]
As much I love missy, we gotta give her a proper name! What are we called? I have a slight preference for Community Software. Since Community Support Software is too long. Community Support sounds like we do SUMO type work. CoSS is to cryptic. Or maybe something completely different?

The readme can use our working Strategic Vision from [slide deck](https://docs.google.com/a/mozilla.com/presentation/d/1c4JBSzGQq7FYNaZgDd0ThNGmXadEvoBYLg_NA7i-DaA/edit?usp=sharing):

The Community Support Software, CoSS for short (previously VMS or MozNet), provides the tools needed for people to contribute to the issues* they care about through Mozilla. A simple, transparent, guided and personalized User Experience ensures that work is surfaced, strategic, done with clear accountability. It will have a near seamless experience with other Mozilla communication and collaboration tools.

Additionally, the CoSS facilitates and enhances the staff/volunteer relationship, allowing for staff or Volunteer Leaders to identify, recognize, and support people at a variety of levels and contribution types.

In 2017, we will create the start of a solution through iterative prototyping with local clubs. With the goal to build key functionality to solve programmatic  needs in a way that is scalable for other teams.

cc @a-kilroy @Pomax @alanmoo @simonwex

**Comment by Pomax** [comment]
If mozilla can have SUMO, CoSS seems fine. Community Software is a bit too open ended to capture the work we'll do in this repo (it is certainly not a repo for all the software-for-the-community we write, nor for software the community wrote for us, for instance). I'd say CoSS?

**Comment by a-kilroy** [comment]
I have been through exercises like this at too many organizations to learn to not have an opinion. I'd say unless anyone hates it to go with CoSS. I don't think people search our repos by project name unless they already know the project?

**Comment by alanmoo** [comment]
💩 ✖️ 0️⃣  here.  Just give it a good description.

**Comment by kristinashu** [comment]
Ok, CoSS it is. @alanmoo are you able to update the name?

**Comment by alanmoo** [comment]
No, I think @simonwex created the repo.

**Comment by kristinashu** [comment]
Name is updated. I'll close this ticket and open a new one for adding to the Readme https://github.com/mozilla/coss/issues/31

**Comment by Pomax** [comment]
Do we know of any crosslinks from issues in other repos to here that need updating?

**Comment by kristinashu** [comment]
I linked some from the Network repo but the links look like the updated automatically https://github.com/mozilla/network/issues/10
