### ISSUE TITLE
Add UI spec/assets via GitHub Pages branch

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#277]
As follow up to #214, I will upload UI spec/assets to a github pages branch of the repo. This will ensure needed UI lives with the repo while also keeping the team updated as changes are made.

@comzeradd let me know once you have a branch ready for this implementation. 👍

**Comment by comzeradd** [comment]
I just created the [`gh-pages`](https://github.com/mozilla/coss/tree/gh-pages) branch and merged your existing code there.

It's already browsable through https://mozilla.github.io/coss/

**Comment by m-branson** [comment]
Awesome! Thanks @comzeradd 🎉

**Comment by m-branson** [comment]
@comzeradd would you be able to update the github pages spec to the Phase 1 prototype? The files are [here](https://drive.google.com/drive/u/2/folders/0B0vmiicLLrGuT1NFanN2YnVTcVU). (I'm not confident in my git skills and would hate to overwrite something!)

**Comment by m-branson** [comment]
Actually @comzeradd let's hold off on this for now. My latest spec export isn't providing asset detail like the previous and I need to troubleshoot. Closing this issue and will reopen a future issue or ping you direct when ready. 👍
