### ISSUE TITLE
Sprint 2 Goal

### ISSUE THREAD

**Issue by hmitsch** [mozilla/coss#28]
* Narrow down on CoSS CMS selection: #25 and #23
* Events Platform research #19
* (clarify with Arielle) compile attributes we’ll want to be able to segment our data by. We currently say ‘issue type’ but what issues. A good way to do this, is to meet with the program people and figure out what questions they want answers too. AKA what would they like their reports to look like.
* noteapp sanity check: do we have any important and/or urgent issues that are not covered in our backlog yet #32
* petition work (finding the successor to NationBuilder): reach out to Matt Holland to bring CoSS on his radar

**Comment by a-kilroy** [comment]
- CMS selected
- Events Platform requirements complete #22 
- Attribute Data work on hold, first draft is expected from Michele W. this week
- Coordination meeting with Matt H is complete
