### ISSUE TITLE
Interview program staff currently using django admin

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#29]
Talk to program staff who are currently using Django as a CMS. Find out what types of updates they are doing with it and identify pain points and wins. 

We can identify staff based on - Mozilla current CMS inventory #24. This will help us decide if Django is a viable CMS platform for us.

**Comment by kristinashu** [comment]
@jvallera @bacharakis how do you currently make updates to your site (example: how do you add a new club to the map)? Do you ever use the Django admin interface?

If not, do you know anyone you does use Django as a CMS?

**Comment by jvallera** [comment]
Yes, I make updates to the Clubs site through the Django admin interface. Here is a list of what I do:

- approve Clubs 
- deactivate Clubs
- change location coordinates (update map)
- edit Club info
- add new Club resources 
- download .csv files of the content

**Comment by kristinashu** [comment]
Awesome thanks! How do you find using it? Can you 'easily' make those updates? Find what you are looking for? What more do you wish you could do (example: update copy, add an image...)?

**Comment by jvallera** [comment]
It is easy to use, but is missing a lot of basic functionality that would allow me to find things and sort data. Right now, I can't really do either through the database. Unless I search each page using command F and/or download the CSV file. Here is my wish list:

1. Give users the ability to edit/update their own Club info
2. Search and/or sort the entire database using names, topics, language, locations, etc. without downloading a CSV
3. Count how many clubs we have in each country or on each continent, etc.
4. Approve and/or deactivate multiple clubs at the same time (currently have to go into each one to update status)
5. See a list of events each club has done (currently is in a separate spread sheet on the events reporter)
6. Copy all the emails from active Clubs without having to download a CSV file.
