### ISSUE TITLE
Add categories or tags in Open Source Clubs enity page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#297]

**Comment by bacharakis** [comment]
Hi Tasos, how can I test that feature?

**Comment by akatsoulas** [comment]
This is about adding tags to clubs through the admin interface. From what I can see there is already a club with a tag (`women`)
https://opensource.mozilla.community/find-club/women-computing-ncc/

**Comment by bacharakis** [comment]
Awesome thank you Tasos
