### ISSUE TITLE
UI needs for Clubs events functionality

### ISSUE THREAD

**Issue by alanmoo** [mozilla/coss#3]
Let's continue the conversations from last week- what are the needs of the events section of the platform, from different perspectives?

**Comment by amirad** [comment]
Wonderful! Adding @jvallera and @bacharakis here too.

**Comment by jvallera** [comment]
Great! can we add a pic of the paper prototype here?

**Comment by kristinashu** [comment]
Here's what I've pulled from the prototypes.

**Create (and edit) event form:**
-  Title, Date, Location
-  Public/Private
-  Picture
-  Description
-  Hashtag
-  Tags/Skills
-  Expected attendance
-  Email attendees

**Event details:**
-  Title, Date, Location
-  Picture
-  Description
-  Hashtag Twitter stream
-  Tags/Skills
-  Club Captain info
-  What was made (hidden until after event)
-  Feedback from attendees (hidden until after event)
-  Curriculum/activity used (hidden until after event)

**Reports/Follow up form:**
-  number of attendees (age, gender)
-  issues/campaign/affiliate
-  what curriculum/activity was used? (link)
-  feedback by attendees (what would you change? where do you need support?)
-  was it what you expected?
-  what was made
-  images/videos
-  survey link (hidden on public view)
-  post event email (hidden on public view)


![img_0143](https://cloud.githubusercontent.com/assets/1068783/22762750/c4795eae-ee15-11e6-8bea-7d472ef0bf32.JPG)
![img_0144](https://cloud.githubusercontent.com/assets/1068783/22762757/ce3b2a1c-ee15-11e6-8311-e6e2fb632968.JPG)
![img_0145](https://cloud.githubusercontent.com/assets/1068783/22762760/d0f1bea6-ee15-11e6-8eeb-6e9af466c8c3.JPG)
![img_0146](https://cloud.githubusercontent.com/assets/1068783/22762763/d2e080ee-ee15-11e6-9e64-b20dd0cf23b1.JPG)

**Comment by jvallera** [comment]
Looks great! This may be already be the plan, but would love to have the feedback from attendees be hidden from public as an option, or only viewable to people who have admin access? I want to be considerate to anyone who is sensitive about who sees the feedback they get.

**Comment by kristinashu** [comment]
Good point! I've added a note in the comment above "hidden form public view - possibly only CC can view".

**Comment by a-kilroy** [comment]
I'd love to call this a UI needs ticket @kristinashu if you are cool with that, can you change the subject and add the label? Then it feels good to have it assigned to you.

**Comment by kristinashu** [comment]
cc @simonwex can you think of anything else to add?

**Comment by alanmoo** [comment]
One thing comes to mind: Where the "share to other platforms" (Meetup?) comes in. Somewhere around the public/private switch?

**Comment by kristinashu** [comment]
I will add these to the wireframes https://github.com/mozilla/coss/issues/38
