### ISSUE TITLE
See how user friendly different Django interfaces are

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#30]
1) Find popular/viable django interface bolt-ons/etc that make working with Django easier from a user/admin point of view.

2) Evaluate selected django interface(s) from a UX perspective. Compare django to wordpress (UI, number of steps to complete a task…)

So far, https://www.django-cms.org/en/ looks like the best option, very Wordpress like.

**Comment by kristinashu** [comment]
@Pomax any luck setting up django-cms?

**Comment by Pomax** [comment]
only on localhost. it's easy enough to set up (literally a few commands) and feels very... for lack of a better term, "wordpressy" down to the whole templating for pages. I've worked my findings into the spreadsheet on which criteria django-cms fulfills.

**Comment by kristinashu** [comment]
Great, is there a way for me to see it? I'd love to try and add/edit pages as a non-engineer. I'm sure @a-kilroy would like to take a looks as well before we commit to it.

**Comment by Pomax** [comment]
I think so, I will see if I can put up a temporary heroku instance for it.

**Comment by Pomax** [comment]
http://django-cms-test-pomax.herokuapp.com/en/?edit should work with admin/admin

**Comment by kristinashu** [comment]
We're going to run with Mezzanine and see how it goes!
