### ISSUE TITLE
About snippet template might not be easy to use for admins

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#323]
About snippets page in cms-admin shows the list of each snippet title. The title field is populated from the info added in Header text (first field from About snippet template) and takes all the formatting text tags from header text.
![about snippet title](https://user-images.githubusercontent.com/5293100/29858911-4bccf694-8d68-11e7-9ff8-2ac0b74ba63c.png)

Also, the Header text is not a required field, so if the admin won't add any text in the Header text field, he/she won't be able to access the snippet, as its title won't be shown in the list of about snippets.
This might be confusing for admins. We should find a way for them to make it easy to create and filter/find snippets.

**Comment by akatsoulas** [comment]
Fixed in #324
