### ISSUE TITLE
 Limit the amount of text that content creators can add in certain fields

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#330]
Currently content creators have no limit on the text to be added to certain fields from templates. 
Also, all the text added by content creators is displayed entirely in the page. 

In the initial UI design (https://mozilla.github.io/coss/#artboard7), a small amount of text is displayed and expand text functionality is available through Read More button, for certain sections: Why, Who.
For the other fields (except Why, Who), I suppose we should limit the number of characters that can be entered.

**Comment by comzeradd** [comment]
The Phase 1 Design contains full text on these blocks. I think we can close this one. @viorelaioia thoughts?
