### ISSUE TITLE
Navigation menu items have no style for active state 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#333]
As per https://mozilla.github.io/coss/#artboard7, the navigation menu items should have different style when active. 
![sections](https://user-images.githubusercontent.com/5293100/29880154-be130a08-8daf-11e7-9956-b2df9097ac2b.png)

**Comment by comzeradd** [comment]
I used this color for the hover action. I thinks it's an overkill to have active status on this menu since we have to track scroll position to do it and it's not visible once you scroll too much.
