### ISSUE TITLE
Update the style of the elements on About page to comply with the UI design

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#336]
On About page, there are elements whose style don't match the one defined in [UI design document](https://mozilla.github.io/coss/#artboard7),  like background color, font type, color, size, etc. 
E.g: nav-about menu should have the backgroung color of #5D5D5D, but we currently have #eee. 
nav-about links have different color + font family.

**Comment by comzeradd** [comment]
@viorelaioia Can you confirm that this is still the case compared to the Phase 1 Design?

**Comment by viorelaioia** [comment]
This is done.
