### ISSUE TITLE
Determine Clubs attributes

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#34]
I've started brainstorming some possible attributes in [this spreadsheet](https://docs.google.com/a/mozilla.com/spreadsheets/d/1daF3fUSTH2yBGnfEUmMgrRNOphkqBlO_rpXAbcS5ZaY/edit?usp=sharing).

@a-kilroy you have a better understanding of the purpose/goals for this so could you please add that context to this ticket?

**Comment by a-kilroy** [comment]
I think I'll take this one off your plate.

**Comment by kristinashu** [comment]
@a-kilroy did you have a meeting about this? I'm curious to see what came out of this.

**Comment by a-kilroy** [comment]
Yup! Though LCM hosted two or three meetings with lots of people to review progress and get feedback. Presentation here https://docs.google.com/presentation/d/1xH8c1ItRqHCmOpGE481IG7FX6VfYrk8uGl8PlIaVBlI/edit?ts=58cc830c#slide=id.g1d2d6ab5c9_0_5 and spreadsheet is here https://docs.google.com/spreadsheets/d/1nlWvT1o7-DGpARVyD1Z7cDadLQysh3igqwnK_vpkBy4/edit#gid=0 Let me know if you want to walk through them.

**Comment by kristinashu** [comment]
Does any of it affect Clubs? I'm wondering if it helps determine any of our filters and tags? E.g. which tags a Club Captain would add to their club description, how we users can filter events...

**Comment by a-kilroy** [comment]
Yea they are going to propose a bunch of stuff. I'm going to close this until we see that list and determine if there is anything we want to add to it.
