### ISSUE TITLE
Photo not shown in the testimony block 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#341]
![photo](https://user-images.githubusercontent.com/5293100/29927644-a09a0592-8e6f-11e7-824e-ba3a8016fd0b.png)
The photo that I used can be found here: https://web-coss-staging.production.paas.mozilla.community/cms-admin/images/7/

**Comment by comzeradd** [comment]
Fixed at b6558d96cbbcd1153f66b48c48509ed3a8bf21e4
