### ISSUE TITLE
Complete Entity Page for QA

### ISSUE THREAD

**Issue by comzeradd** [mozilla/coss#355]
- [x] Align with Phase 1 Design
- [x] Make Image Gallery dynamic
- [x] Add Open Source Clubs Profiles & Captains
- [x] Add dynamic Profiles

**Comment by bacharakis** [comment]
Hi there, how can I test this feature?

**Comment by akatsoulas** [comment]
Basically this is the functionality for adding Open Source Clubs (entitites). There are already a few of them in prod so probably we are OK with this. We just need you to confirm that you did not face any problems and everything is good on your side.

**Comment by bacharakis** [comment]
Awesome thank you Tasos
