### ISSUE TITLE
UX/UI Design: US Pilot Program Static Banner (Old Site)

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#358]
**Problem statement:** US users may end up at the old (international) site and not understand where they are/how to get to the US pilot site.

**Phase 1 Solution:** Create a static banner to be placed at the top of the site that provides information for US users re: new site w/link.

**Suggested copy:** “Visiting from the US? We’re running a pilot to support open source clubs in the US that you might be interested in checking out. link …”

**Comment by m-branson** [comment]
@bacharakis @LucyeoH -- Here's a simple banner for implementation on the current campus site. Images of the banner on it's own; with spec; and mocked up are shown below. 

Feel free to edit copy and style(s) as you need. Color was tough next to the current green header so I went with black. I also simplified copy a bit for users to 'quick read'. :)

The flag and arrow icon SVGs can be found [here](https://drive.google.com/open?id=0B0vmiicLLrGuQWxJb0VMRFhhdU0).


**Banner**
![pilot-banner.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/5205e77e-ddf7-4612-84d6-36d48d9397a4)

**Spec**
![pilot-banner-spec.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/b8642c6f-e9f5-451d-a3ce-aac1a35db750)

**Mockup**
![International-Site-Banner.jpg](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/504dde5f-a402-4888-9d82-b03d21bcf1a0)

**Comment by LucyeoH** [comment]
Looks great! Anyway we could make that tiny flag star spangled? If that's
more than 5 mins work ignore this request. Just thought it would be fun...

**Comment by m-branson** [comment]
Hey @LucyeoH somehow missed your response to this. Star spangled is definitely more than 5mins. :( Christos may be able to find a US flag icon to drop in there at the same size though? I'm going to close this one out but please reopen if we need to iterate further! Thanks. :)
