### ISSUE TITLE
UX/UI Sketch file cleaning

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#359]
Specifically: organize type styles to improve ease of future iteration + design hand-off.

**Comment by m-branson** [comment]
@comzeradd also pointed out discrepancy in use of Open Sans Light vs. Regular. Will align file with OS Light baseline and push to prototype.

**Comment by m-branson** [comment]
Sketch file has been cleaned, organized and text styles are up-to-date. [File can be found here](https://drive.google.com/open?id=0B0vmiicLLrGub3ZyS2stdW9saXc).

@comzeradd @viorelaioia when you're working with the [Phase 1 Prototype](http://invis.io/AZDAP6MPT) all of the text styles should be correct. Baseline body copy for the site is Open Sans 'light' @ 16px. There are instances of Open Sans 'regular' (navigation); 'semi-bold' (text links); and 'bold' (button text). This will help with legibility/emphasis throughout the site. Let me know if you run into something odd. :)

**Comment by comzeradd** [comment]
Thanks @m-branson! 🚀 

Is this reflected on Invision too? For instance on the homepage if I pick the header text, right below the Intro Headlne, I see: Typeface: Open Sans. Is that the Regular variant?

![screenshot from 2017-09-08 15-52-45](https://user-images.githubusercontent.com/939357/30212569-2b759908-94ae-11e7-849f-2c8e6af2678e.png)

**Comment by m-branson** [comment]
Hey @comzeradd, I've noticed that InVision has changed the variants to the following for Open Sans (look in the _WEIGHT_ attribute field):

- Regular = _normal_
- Light = _300_
- Semibold = _600_
- Bold = _bold_
- Italic = _italic_

Hope this helps?
