### ISSUE TITLE
Header Scroll Behavior/Design

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#366]
On scroll, the site navigational header should 'stick' and minimize in size to 70px height. Logo reduces to 'm' bug with 'ossn' to the right in black Zilla Slab typeface.

![ white-scroll.jpg](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/9ca441fe-280d-4203-a72f-c91b2736120d)

![ orange-scroll.jpg](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/9563d685-5e3c-47aa-abbd-85d359fcf661)

**Comment by viorelaioia** [comment]
Logo is not displayed at all when scrolling down on Activities, Resources and FAQ pages. ![Screenshot-2017-9-22 Find An Activity.png](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/0fc62a32-defa-4cbd-8800-5bbf4c702a57)

**Comment by bacharakis** [comment]
Tested and works. Thank you all!
