### ISSUE TITLE
Determine first pages

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#37]

**Comment by kristinashu** [comment]
Will look at the wireframes and determine which pages to tackle first (identify easy wins and key priorities).

**Comment by kristinashu** [comment]
To focus our efforts, I will expand on [wireframes](https://invis.io/72AN1X8WT), do testing and design in the same order the pages will be built (so as not to block engineers or get too far ahead):
- About
- Become a Club Captain form
- Individual Club details page
- All Clubs overview page (thumbnails of each club with search, filters)
- Home
- Planning overview (thumbnails that link to external resources)
- Activities overview (thumbnails that link to external activities)
- Create an Event form
- Individual Event details
- Events overview (thumbnails of each event with search, filters)
- Planning details 
- Activities details

@Pomax does this sound like a reasonable order?

**Comment by kristinashu** [comment]
@a-kilroy I'd like to clarify what our approach is. Are we:

Make all our wireframes, user test all wireframes, design all pages, user test all page, build all pages and then user test the built website.

Or, are we doing all those steps but for individual 'chunks'. Eg make About page wireframe, user test About page wireframe, design About page, user test About page, build About page and then user test the built About page. And then move onto the next chunk like Become a Club Captain. (this is what I think we're doing)

Or are we doing it my feature. Eg all static content on all pages... I'm not as sure how this one would look. (maybe we're all do a bit of this for things like search/filters functionality)

**Comment by a-kilroy** [comment]
I am seriously not even getting messages you tagged me in. I pulled this up to comment on your previous comment on this ticket saying we might want to adjust order to reflect Simon's focus on events.

Anyway, do you still have questions on approach? From our call it seemed like you and Megan had  worked out a plan.

**Comment by kristinashu** [comment]
Yes, updating this list to: _(but I'm sure it will change again...)_
- About
- Events
   - Create an Event form
   - Events overview (thumbnails of each event with search, filters)
   - Individual Event details
- Clubs
   - Become a Club Captain form
   - Individual Club details page
   - All Clubs overview page (thumbnails of each club with search, filters)
- Home
- Planning overview (thumbnails that link to external resources)
- Activities overview (thumbnails that link to external activities)
- Planning details 
- Activities details

We will complete all wireframes and testing before moving on to any visual design.
