### ISSUE TITLE
Text style for quotee is different than in the UI and the quotation mark next to the picture is not displayed

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#373]
Homepage link: https://opensource.coss-staging.mozilla.community/
![quotee.jpg](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/5ec90ceb-bf0d-496e-bbc1-1aa22b03f1d5)

**Comment by viorelaioia** [comment]
The style of the quotation mark doesn't match the one from UI:
![quotation_mark.jpg](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/92854436-586f-4070-946b-cb06ec077bd2)

**Comment by comzeradd** [comment]
Can you do another check for the quotation mark? I'm getting some weird results from ZillaSlab for this. Nightly doesn't render it in an italic font-style and it looks completely different.
