### ISSUE TITLE
Wireframes for Clubs

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#38]
Create Wireframes for Clubs Prototype to test then build.

**Comment by kristinashu** [comment]
I will do some initial high-level wireframes to help us better visualize what we need. 

These will help clarify/determine:
- what the CMS needs are (show types of pages Program Staff would build, what would be edited...) #30 
- attributes #34
- dependencies and what the key pages are #37
- what content/copy we will need #20
-

**Comment by kristinashu** [comment]
Here's a _super_ rough start. There are a lot of blank pages and every details needs to be thought through a bunch more but this should help us visualize things and make sure we're all on the same page.

https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087690_Home 

cc @a-kilroy @Pomax @alanmoo

**Comment by kristinashu** [comment]
This ^ is based on the following IA:

<img width="1110" alt="screen shot 2017-02-27 at 5 25 03 pm" src="https://cloud.githubusercontent.com/assets/1068783/23387499/bf661dfc-fd11-11e6-9d72-e14964bdb60f.png">

and how I see the pages being organized:
<img width="910" alt="screen shot 2017-02-27 at 5 24 43 pm" src="https://cloud.githubusercontent.com/assets/1068783/23387498/bf65cf14-fd11-11e6-8d43-5689fc923492.png">

**Comment by kristinashu** [comment]
@LucyeoH @bacharakis @jvallera @amirad I would love to start getting some thoughts and feedback from you on these [wireframe](https://projects.invisionapp.com/share/72AN1X8WT#/screens/221087690_Home) (but no rush, I believe some of you are on the road...).

They are still considered quite rough but I want to make sure I'm heading in the right general direction. Some high-level feedback would be great (eg let me know if I'm missing an entire page or section or if you think we should remove entire page or section...). 

At this moment, I'm less concerned about the smaller details like a particular form field or tag, but having said that, please still feel free to and comments in if anything comes to mind. I've created a ticket for each page where we can start to dive into the details. Please start dumping any relevant info in there (docs, links, feedback, comments...). 

Please ping me if you want to talk anything over. It would be great to all sync up in person but also don't want to delay things while trying to find a time.

**Comment by jvallera** [comment]
Wow @kristinashu these look great! this makes me very happy. I will comment directly in individual issues. One thing we will need to decide on is how much we include about regional coordinators. I prefer not to have an open application on the site and to keep it invite only and/or do an open call once or twice a year. I love the [page ](https://learning.mozilla.org/en-US/clubs/coordinators)we currently have to recognize RC's and would love to incorporate that as well. Each RC has unique url to their profile which is great for vouching purposes. Until we decide on that I think it might be best to showcase the RC profiles somewhere, but not have an application....instead just text describing the process and how to get more info about becoming an RC.

**Comment by kristinashu** [comment]
Good point Julia! I'm realizing these wireframes are really lacking people. I'd also love to showcase some people on the home page as well, to really highlight how this is about bring people together and that there are tons of people already involved.

**Comment by kristinashu** [comment]
Arielle has provided some great feedback in this pdf [AKcomments-Clubs-wireframes-01.pdf](https://github.com/mozilla/coss/files/848898/AKcomments-Clubs-wireframes-01.pdf) (while she was on a plane). I will be working on these updates.

**Comment by m-branson** [comment]
Closing this issue, will revisit Clubs wireframe needs after all hands.
