### ISSUE TITLE
Add a social component for OSC.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#390]
We need a content block, editable through the admin, that can be used in multiple templates and can provide integration with social providers.

**Comment by bacharakis** [comment]
Hi there, how can I test this feature?

**Comment by akatsoulas** [comment]
@bacharakis this is about adding the social links (see screenshot) in an entity page through the admin interface.

![screenshot-2017-10-18 rensselaer center for open source rcos](https://user-images.githubusercontent.com/900565/31720077-42dbb2aa-b41e-11e7-9382-c7d90ab69bd3.png)

**Comment by bacharakis** [comment]
Awesome thank you so much Tasos!
