### ISSUE TITLE
Activities page - activity last text row is not shown entirely 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#396]
![Screenshot-2017-9-12 Find An Activity - open source clubs.png](https://images.zenhubusercontent.com/589c8bd951aa2c305773eb64/475cc643-751e-4616-a177-cc00e2d6ff79)

**Comment by m-branson** [comment]
@comzeradd can we put a character limit on these descriptions? Or simply truncate them with an ellipsis `...` ?
