### ISSUE TITLE
Launch schedule

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#401]
- [x] schedule CMS training
- [x] make sure Lucy/Christos understand how to file bugs

**Comment by hmitsch** [comment]
# The site is *launched as of 22 SEPT 2017*m 5.10pm CEST!

**Comment by hmitsch** [comment]
* **MON 25 SEPT:** Program managers will send a launch announcement to the students.
* **THU 28 SEPT:** Work on Milestone 2 desires starts.
* **Next weeks:** Program managers will reach out to students to walk them through the program and the website.
* **by 23 OCT:** Milestone 2 roadmap exists
