### ISSUE TITLE
Use GTM for analytics.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/coss#434]

**Comment by akatsoulas** [comment]
We want to move to GTM for Google analytics.

**Comment by hmitsch** [comment]
Works!

Link clicks (including outbound links) are now tracked in Google Analytics.
![image.png](https://images.zenhubusercontent.com/57641233bf93871ccd9cc8fe/38d5e1d2-a25c-42d9-8577-5be2e723f5da)

Thank you!
