### ISSUE TITLE
Share entity page on facebook doesn't work as expecetd

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/coss#436]
After click on the Facebook icon on entity page, even if we choose to cancel or share the post, [https://www.facebook.com/dialog/return/close#_=_ ](https://www.facebook.com/dialog/return/close#_=_) page is returned (on FF 55). On FF Nightly, the site is closed.
Suggestion: Open a new tab when trying to share a post on facebook.

**Comment by bacharakis** [comment]
I tested and it works now.

Thank you

**Comment by akatsoulas** [comment]
I am closing this issue per last comment.
