### ISSUE TITLE
Try to use Mezzanine

### ISSUE THREAD

**Issue by Pomax** [mozilla/coss#44]
mezzanine
- [x] set up a mezzanine branch
- [x] add mezzanine to this branch in a way that everyone can "easily" install it
- [x] make sure the code taps into env vars, not just settings.py / local_settings.py, so we can deploy it on heroku
- [x] set up an app that can deploy off of this branch on heroku
  - set up as `mezzanine-cms-experiment`, won't be live quite yet, env vars need to be sorted out first

first steps:
- [x] add some assets for creating a simple landing page
- [x] put a moz://a logo on mezzanine
- [ ] we want to create the template for the landing page
- [ ] we want to style this landing page (mofo bootstrap perhaps)

**Comment by kristinashu** [comment]
Assets folder should have:
- Mozilla Clubs logo for the header 
- Mozilla logo for the footer. Could do something like this (let me know if that is too complicated for these purposes)  
<img width="1018" alt="screen shot 2017-03-02 at 2 12 49 pm" src="https://cloud.githubusercontent.com/assets/1068783/23529481/a902ac18-ff52-11e6-803b-a607f0c2448e.png">

**Comment by Pomax** [comment]
This looks easy enough - as a static footer we should be able to have an image living next to a text block. The rest is essentially CSS magic.

**Comment by a-kilroy** [comment]
Closing. Let me know if this is incorrect
