### ISSUE TITLE
Benchmark CMS

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#45]
@m-branson since you have tested an array of CMS, it would be great if you could benchmark a few. Not that we would use them, just so we can show what an ideal look would be and what type of elements we should strive for.

Probably just need to grab some screen caps and pointing out what you like about them, but open to whatever format you think works best.

Google slides would be great so that anyone can collaborate on it if they want.

**Comment by m-branson** [comment]
Fantastic, thanks @kristinashu ... I have a couple hours this week and early next that I can put toward this. 

Google slides sounds great.

**Comment by m-branson** [comment]
CMS Benchmarking slide doc is now available [here](https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing)...will continue to populate over the coming days with annotation around Grav, Squarespace and Mozu.

**Comment by kristinashu** [comment]
Damn! Craft is slick!

**Comment by m-branson** [comment]
Totally! Might be worth checking out a [demo](https://demo.craftcms.com/) if you want to nerd out a little bit (this reminds me that I should link to the CMS sites in the doc). 

If we could somehow pull some of that functionality into our build, would be fantastic. Will have a couple more slides to add for Craft as well. :)

**Comment by m-branson** [comment]
Spent time today adding annotation for Grav and images for Webflow to the [doc](https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing).

**Comment by m-branson** [comment]
Added images for Squarespace & began their annotation today ([doc](https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing)).

**Comment by a-kilroy** [comment]
Really awesome work!

**Comment by m-branson** [comment]
Thanks @a-kilroy ... added a couple more slides (and hopefully some more context) for Webflow. Annotation for Squarespace and Webflow is complete.

Please let me know if there are questions and/or comments. 👍

**Comment by a-kilroy** [comment]
Cool. I downloaded it for plane ready for tomorrow.
