### ISSUE TITLE
Design barebones landing page for Clubs

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#46]
I'll design a simple landing page for Clubs that @Pomax @alanmoo can use for a quick prototype to test Mezzanine.

Related to https://github.com/mozilla/coss/issues/44

**Comment by kristinashu** [comment]
The styling will most likely look more like the [network site](https://projects.invisionapp.com/share/ZJ9YTAGEA#/screens/216715355) (Mozilla's new branding) rather than mofo-bootstrap.

**Comment by kristinashu** [comment]
Mocked up a simple landing page: https://redpen.io/p/do5730fd388d326fa3

It's a bit of a mix of the old branding and new. I stuck with Fira font, but used black instead of dark grey we used to use. @Pomax @alanmoo let me know if it should be even simpler.

![cms-prototype 2x](https://cloud.githubusercontent.com/assets/1068783/23533549/4bf5c5d6-ff67-11e6-8f6e-73820845c972.jpg)


Tomorrow I'll add a slightly more souped up version: adding in a 3up feature, maybe our new typefaces, and some footer links?? Then engineers can decide how much to actually build.

<img width="590" alt="screen shot 2017-03-02 at 4 41 52 pm" src="https://cloud.githubusercontent.com/assets/1068783/23533541/4499ec7c-ff67-11e6-8220-67c547eb6dda.png">

**Comment by kristinashu** [comment]
Here's the more souped up version: https://redpen.io/p/do5730fd388d326fa3

@Pomax @alanmoo feel free to use as much or little from this version as you like. It uses a lot more of the styles from the Network site (the direction our brand is heading in). 

![temp landing page copy 2x](https://cloud.githubusercontent.com/assets/1068783/23562187/523ca6fa-fff6-11e6-9f42-d22c0d079fd6.jpg)

**Comment by kristinashu** [comment]
Ok, also added a third option which is the simplest https://redpen.io/p/do5730fd388d326fa3 

If you feel comfortable with this general direction then I'll prep all the assets and provide some design specs.

**Comment by a-kilroy** [comment]
Looking good!
