### ISSUE TITLE
Font inconsistencies

### ISSUE THREAD

**Issue by bacharakis** [mozilla/coss#461]
The font and its size is different from the wireframe/mockup Megan has created which creates a totally different user experience.

**Comment by a-kilroy** [comment]
@bacharakis We need screenshots and comments for this one. It's quite possible that you are overriding fonts in the rich text fields but we need specifics to tell what's happening.

**Comment by bacharakis** [comment]
Sorry you are right, it also took my some time to understand what was different on the live website compared to the mockups.
You can check the two following screenshots for example:
![Screenshot from 2017-09-20 08-12-02.png](https://images.zenhubusercontent.com/57334440bf93871ccd9adcd3/68796b4a-8b74-4d2f-8477-6c866c010dac)![Screenshot from 2017-09-20 08-12-33.png](https://images.zenhubusercontent.com/57334440bf93871ccd9adcd3/476c0abc-9368-4fcc-9030-ab68068b7b13)

**Comment by a-kilroy** [comment]
@bacharakis @comzeradd so it looks like this is in the rich text field for the intro text here. CHRISTOS if you see more examples please grab screenshots. NIKOS lets see if we can use this to start to find out what's happening.

**Comment by comzeradd** [comment]
The fix is now on production. Font inconsistencies are now fixed for the About page.
