### ISSUE TITLE
Font for links

### ISSUE THREAD

**Issue by bacharakis** [mozilla/coss#462]
Linked words have almost the same font (size, color) with the rest of the text so you can't tell what is a hyperlink and what not.

You can check the about and resources page in particular.

**Comment by a-kilroy** [comment]
@bacharakis same comment about screenshots. This one took me a bit to figure out what you meant.

**Comment by bacharakis** [comment]
Apologies about that. In the attached screenshot you can see a block where it's hard to understand what is link and what is just text![Screenshot from 2017-09-20 08-06-36.png](https://images.zenhubusercontent.com/57334440bf93871ccd9adcd3/d1c9b008-dd1c-4647-908b-a1a54591eff2)
