### ISSUE TITLE
Improve opengraph metadata

### ISSUE THREAD

**Issue by johngian** [mozilla/coss#479]
* Use club photo on when sharing in FB (instead of logo)
* Use the page logo as a generic photo (in pages not referring to a club)
* Allow ``og:..`` metadata to be defined in wagtail admin

**Comment by hmitsch** [comment]
Testing via: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopensource.mozilla.community%2Ffind-club%2Frit-linux-users-group%2F

Current result:
![image.png](https://images.zenhubusercontent.com/57641233bf93871ccd9cc8fe/8147fc8b-1b88-4b12-932c-a75bab9dce06)

**Comment by hmitsch** [comment]
Looks great!

![image.png](https://images.zenhubusercontent.com/57641233bf93871ccd9cc8fe/49655a09-f93c-4f37-99fb-b1de63f379e6)
