### ISSUE TITLE
Copy for Clubs about page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#49]
An about/landing page will be the first section of the website we tackle. We should start gathering, synthesizing and editing copy for it.

We can start by dumping everything we think could be there into [this doc](https://docs.google.com/a/mozilla.com/document/d/1YgoBZ8eCWN4d_20nNkElRSuEQpEPBgsgx7e4zFlapZU/edit?usp=sharing). This won't be final copy in any way but will be a good exercise to start figuring out how we want to talk about 'clubs' in the new expanded sense, in a safe nonpublic space. But the real goal for this is to have something to start the page layout with and then eventually start editing it down.

**Comment by kristinashu** [comment]
@LucyeoH @bacharakis @jvallera @amirad would you be up for taking a stab at this ^

**Comment by kristinashu** [comment]
Thanks everyone for adding your copy! 

@a-kilroy would you be able to wrangle a copy writer to take a look at what's there? [copy doc](https://docs.google.com/a/mozilla.com/document/d/1YgoBZ8eCWN4d_20nNkElRSuEQpEPBgsgx7e4zFlapZU/edit?usp=sharing)

**Comment by a-kilroy** [comment]
Just to close the loop I sent this to Alex, our marketing/press team member to help make this extra awesome.
