### ISSUE TITLE
Gather images for Clubs website

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#50]
Start a folder to consolidate all our images that we can then pull from for the website comps.

**Comment by a-kilroy** [comment]
@kristinashu should we set up a final visual design epic for this and #49

**Comment by kristinashu** [comment]
I'd love be able to pull from an image bank. @LucyeoH @bacharakis @jvallera @amirad can you please add whatever images you have here? Either add links (url to flickr album, dropbox folder...) to this ticket or add them as a sub folder here:
https://drive.google.com/open?id=0B2irLVDJivhLZFhKck9wWjQ0SVU

**Comment by jvallera** [comment]
Sure thing:

Mozilla Clubs Training CapeTown 2016: https://www.flickr.com/photos/87282947@N06/albums/72157667879028410
Mozilla Clubs at All Hands in London: https://flic.kr/s/aHskCPoJRr

@amirad has amazing pics but not sure if best shared through flickr or elswhere, so will wait for her to add. 

@kristinashu would be great to have a central image bank that we use moving forward. Photos come in from all over (events gallery, facebook, discourse, etc.) so it is hard to collect all of them. Should we have something on the site when people share events like a checkbox that allows them to add a photo to Clubs image bank?

**Comment by amirad** [comment]
Feel free to take a look here and ping anyone directly if you want to use their pictures https://www.facebook.com/groups/mozillaclubs/ 

I have these two albums:
https://www.flickr.com/photos/amirad/sets/72157668339120651
https://www.flickr.com/photos/amirad/sets/72157666127395174

And will be uploading more pics to my flickr this week from our recent trips.

**Comment by a-kilroy** [comment]
@LucyeoH @bacharakis anything from you two?

**Comment by bacharakis** [comment]
Apologies for the late reply!

I think that for that use, we can share the images we have in our website already.

https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/resources.jpg
https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/photo_clubs2.jpg
https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/photo_clubs3.jpg
https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/photo_clubs3.jpg
https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/photo_top.jpg
https://github.com/mozilla/mozilla-campus-clubs/blob/gh-pages/static/img/photo_clubs1.jpg

**Comment by kristinashu** [comment]
Thanks everyone, I've added these to the folder!

**Comment by amirad** [comment]
Sneaking in this album that I just uploaded @kristinashu  https://www.flickr.com/photos/amirad/albums/72157678688588433

**Comment by kristinashu** [comment]
Awesome, looks like it was a great trip!
