### ISSUE TITLE
Admin UX Assessment

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#500]
Now that the CoSS website utility is up and running (woot!) it's time to start identifying how we want to shape the admin experience.

As a first step I will begin a UX Assessment this sprint to identify potential improvements. This document will serve as a source of truth as the CoSS team begins to triage and roadmap next steps.

*[update sprint 17]*
CoSS team has determined need for continued UX Assessment, to be completed this sprint for triage and roadmap in sprint 18.

**Comment by m-branson** [comment]
@a-kilroy @akatsoulas @johngian @comzeradd @hmitsch 

I've started a [UX Assessment](https://docs.google.com/a/mozilla.com/document/d/1J-thrNO6q83uj25XVDy7fKuvuX1eAVJPuLMICyFngNw/edit?usp=sharing) for our current CoSS Website Utility Admin. Before I go much further I'd like to have you all read through it and have us all regroup on the direction we want to take. I have quite a few questions and want to avoid making assumptions re: our goals for this experience. Let's get aligned on what we want out of this utility and determine how best to approach it (e.g. continue the assessment? wireframe some user flow changes and test? begin a restructure of the experience?).

I've also referenced this in the doc, but a good time to also review our earlier [CMS Benchmarking](https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing) for UX/UI.

**Comment by hmitsch** [comment]
Had a look at the UX Assessment. It is awesome. Added a few comments. Overall I really like the direction. 

Concerning customization, I guess we should do some t-shirt sizing to identify cost/benefit of the proposed changes. Maybe we also want to time box customization to X amount of days?

**Comment by m-branson** [comment]
Thanks @hmitsch, helpful feedback. There are various levels of detail this assessment can take, at the moment I'm taking a higher level approach as I imagine there will be unforeseen technical debt associated with various aspects. I will continue to populate the assessment next sprint and ideally we can prioritize when @a-kilroy is back? Unless this is something we want to do sooner?

> Concerning customization, I guess we should do some t-shirt sizing to identify cost/benefit of the proposed changes. Maybe we also want to time box customization to X amount of days?

Absolutely. I'm concerned that we could take on too much customization initially and distract from more important, overall experience and structural changes.

**Comment by a-kilroy** [comment]
This is so great! For this sprint, I'd like to prioritize a technical assessment (and potentially some work based off assessment) for your dashboard and navigation feedback. These feel like low hanging fruit. I think we should tackle the log in in a separate sprint soon, if not sprint 18.

**Comment by m-branson** [comment]
Hi @a-kilroy, I've added some more to the [UX assessment](https://docs.google.com/a/mozilla.com/document/d/1J-thrNO6q83uj25XVDy7fKuvuX1eAVJPuLMICyFngNw/edit?usp=sharing) and feel that a technical assessment can absolutely happen in the upcoming sprint. Holler with questions!
