### ISSUE TITLE
Add URL to GitHub project URL field

### ISSUE THREAD

**Issue by sumnerevans** [mozilla/coss#502]
There is no URL on the GitHub project. This will help people find where this awesome site is deployed.

![No description, website, or topics provided.](https://user-images.githubusercontent.com/16734772/30949637-d8f7544c-a3d4-11e7-930e-ab82c2893527.png)

**Comment by hmitsch** [comment]
Thanks for catching this @sumnerevans! I added a link to an [early Discourse post](https://discourse.mozilla-community.org/t/iam-coss-work-week-jan-2017/13497).

By the way, you can see CoSS in action on the [Open Source Student Network](https://opensource.mozilla.community/).

-Henrik
