### ISSUE TITLE
UI issue on resource page

### ISSUE THREAD

**Issue by DineshMv** [mozilla/coss#504]
Issue with resource name & Git profile on [Resources](https://opensource.mozilla.community/resources/) page.
![3-ui](https://user-images.githubusercontent.com/10209762/30959023-91a7bd06-a45c-11e7-8ece-e74c2fadeaac.png)

**Comment by akatsoulas** [comment]
Thanks @DineshMv for filing this! @comzeradd can you have a look?

**Comment by comzeradd** [comment]
@DineshMv it seems that the mentor's profile picture is not rendered at your browser for some reason. We should definitely account for that case. Are you on Firefox or some other browser?
