### ISSUE TITLE
OSSN Logo Update

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#517]
The [Mozilla Brand Guidelines](https://mozilla.ninja/expression/) have been udpated and require a change to the OSSN logo. Will update and share for implementation.

**Comment by m-branson** [comment]
OSSN wordmark (logo) has been updated to align with the latest brand updates. PNGs posted inline and SVGs attached below. Full files are available on g-drive [here](https://drive.google.com/open?id=0B0vmiicLLrGuNHRISmpWbWVpbVk).

*Primary Black & White*

![ossn-logo-bw.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/b96b0efe-f1eb-4323-94ad-7ad750a4bb5d)

*One Color White* (not 'visible' here but posting for file availability)

![ossn-logo-one-color-white.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/9e351308-659f-4ed7-a321-4a455edee738)

*One Color Black*

![ossn-logo-one-color-black.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/e7977ee2-7234-4f0a-93b1-4ecdbdb28a09)

[https://app.zenhub.com/files/80838213/53d4dc54-64e6-4638-bb83-bb986cadc36e/download](https://app.zenhub.com/files/80838213/53d4dc54-64e6-4638-bb83-bb986cadc36e/download)

**Comment by m-branson** [comment]
Hi @comzeradd, thanks for the quick work getting this on stage! A couple things before we push to prod:

• Logo's sizing should be 50px height x 155px wide. Looks like the header size should also reduce to 90px height once this change is made.
• The minimized version of the header with `m - ossn` isn't on brand and we need to remove it. (Looks like the 'm' is only meant to be used as a social media icon or favicon, not as a logo.)
• I forgot to make a primary white version! This is a version with white text and the black/white mozilla logo to be used on the colored header. Here's a PNG, an SVG is also attached via ZIP and everything is updated on [g-drive](https://drive.google.com/open?id=0B0vmiicLLrGuNHRISmpWbWVpbVk).

![ossn-logo-white-primary.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/13d023a4-0fa8-4f42-98e1-4f4e9fb7d41b)

[https://app.zenhub.com/files/80838213/48301b26-fcf8-409b-8209-35134af9b02f/download](https://app.zenhub.com/files/80838213/48301b26-fcf8-409b-8209-35134af9b02f/download)

**Comment by comzeradd** [comment]
New logos are now on stage.

**Comment by m-branson** [comment]
Reviewed, looks great. Thanks @comzeradd 👍
