### ISSUE TITLE
Wireframes for Club Captain application form + confirmation 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#52]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at these pages and iterate on it.

![apply form 2x](https://cloud.githubusercontent.com/assets/1068783/23723873/a57de4ca-03ff-11e7-87d8-59ef41eee61c.jpg)
![thanks for applying 2x](https://cloud.githubusercontent.com/assets/1068783/23723874/a57ef9a0-03ff-11e7-979d-056b498c7fb9.jpg)

**Comment by jvallera** [comment]
Will there be an "agreement to terms" or something like that? we currently have this on our application and need to include it here. This is our Club Leader agreement [form](https://docs.google.com/document/d/1DIAXJCGzTGgjRMRrjkhd4Q63XBxOAQiR-xdOV3jjLW4/edit?ts=57965cef&pli=1) we created with LEgal, so it would be great to link to or have people agree to it in applying.

**Comment by kristinashu** [comment]
Cool, I've add the checkbox and link to the application page and also added a Legal page to the wireframes (as well as some other changes).

Closing this ticket but feel free to add any other feedback in [InVision](https://invis.io/72AN1X8WT).

![apply form 2x](https://cloud.githubusercontent.com/assets/1068783/24525548/8a8591ac-154f-11e7-925f-f3039a39ae5f.jpg)

![legal 2x](https://cloud.githubusercontent.com/assets/1068783/24525549/8a94562e-154f-11e7-9c40-1173276127dc.jpg)
