### ISSUE TITLE
Wireframes for Club details page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#53]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

![club details 2x](https://cloud.githubusercontent.com/assets/1068783/23723955/ee6f7d6a-03ff-11e7-92ad-6dd19c428dcf.jpg)

**Comment by jvallera** [comment]
Love this. Is it possible for Club Captains to choose how much of this page is visible? They may opt to keep the exact location hidden or remove the "join this club" button for example.

**Comment by kristinashu** [comment]
Yes! This is an option in the [application form](https://invis.io/72AN1X8WT#/221087730_Register_Form) (and edit). 

I made some updates based on feedback, any other updates can be made in [InVision](https://invis.io/72AN1X8WT) and at the comp stage.
