### ISSUE TITLE
Wireframes for Activity Detail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#54]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

![activity detail 2x](https://cloud.githubusercontent.com/assets/1068783/23724035/300c725a-0400-11e7-9797-91f3d4b5b2fb.jpg)

**Comment by jvallera** [comment]
You probably thought of this already, but would love Captains to be able to "save" or "like" activities and then be able to see what those are when they are logged in. And super cool extra feature would be to "recommend" an activity to another Club Captain or "vouch" for an activity so we can see which activities are the most popular.

**Comment by comzeradd** [comment]
I'm closing wireframe issues, since we now have the style guide #214
