### ISSUE TITLE
Update Admin to reflect most recent branding

### ISSUE THREAD

**Issue by comzeradd** [mozilla/coss#558]
That includes font, colors, logo, etc

**Comment by comzeradd** [comment]
I have already opened a [PR](https://github.com/mozilla/coss/pull/564) addressing some of these (especially fonts).

@m-branson Regarding colors, what would suggest? Should we use something from the [Visual Elements guide](https://mozilla.ninja/visualelements/)?

**Comment by m-branson** [comment]
@comzeradd The SSO Dashboard is a great place to start typography and color style wise. As for primary color use, perhaps variations of the Mozilla Neon Blue?

[color-scales.pdf](https://github.com/mozilla/coss/files/1447999/color-scales.pdf)
