### ISSUE TITLE
Optimize image sizes and quality

### ISSUE THREAD

**Issue by comzeradd** [mozilla/coss#568]

**Comment by comzeradd** [comment]
Wagtail [already](http://docs.wagtail.io/en/v1.11.1/advanced_topics/images/renditions.html) creates variations of images based on the template tag used. It calls these renditions. These variations are created and saved during first invocation of the image.

Things we can do to optimize images:
* Check all image tag and make sure they have a proper `size` attribute based on their place in the UI
* Try lowering `WAGTAILIMAGES_JPEG_QUALITY`. This currently at 85, which is [considered](http://docs.wagtail.io/en/v1.11.1/topics/images.html#image-tag) high. This won't adjust existing images. In order for this to be applied to existing images we will need to [manually](http://docs.wagtail.io/en/v1.11.1/topics/images.html#changing-globally) delete existing rendition.

/cc @akatsoulas

**Comment by krishamehta** [comment]
Can I help with this?

**Comment by comzeradd** [comment]
Hi @krishamehta, thanks for interest to contribute!

There is a [PR already merged](https://github.com/mozilla/coss/pull/569) for this. We just need to test it and see how good it works before we close this one. But feel free to add any suggestions or check any other open issue.
