### ISSUE TITLE
Wireframe for Event Details

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#58]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

![event detail 2x](https://cloud.githubusercontent.com/assets/1068783/23724191/b223d4ea-0400-11e7-937a-5031aa0ea9e2.jpg)

**Comment by kristinashu** [comment]
Few updates based on requirements:

![event details 2x](https://cloud.githubusercontent.com/assets/1068783/23873567/b9fdd114-07ef-11e7-8ccf-2531cb78dfcc.jpg)

**Comment by kristinashu** [comment]
Made updates based on feedback, any other small updates can be made in [InVision](https://invis.io/72AN1X8WT) and at comp stage.
![event details 2x](https://cloud.githubusercontent.com/assets/1068783/24480749/d05852c4-149a-11e7-844e-9f33f3253729.jpg)

**Comment by a-kilroy** [comment]
Really like these updates.

**Comment by bacharakis** [comment]
I really love the update too! My only suggestion and this maybe because I am used to it, is to put the organizer in the right column under the RSVP. I

**Comment by kristinashu** [comment]
Thanks for the feedback! I've made that update in InVision and will explore a bunch more layout options in the design stage.
