### ISSUE TITLE
Wireframe for Home page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#61]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

![home 2x](https://cloud.githubusercontent.com/assets/1068783/23724270/f221e960-0400-11e7-922c-2e36b2392b22.jpg)

**Comment by kristinashu** [comment]
I would like to feature people more on this page.

**Comment by kristinashu** [comment]
Feedback from Lucy has been that this landing page isn't specific enough for the Campus Clubs audience. We are exploring the option of having a dedicated landing page for Campus. I've outlined this feedback [here](https://docs.google.com/a/mozilla.com/presentation/d/1Ou6CFoDKHzbwAYKKtjADpoFp6zftEVklzQeWJq_Uh3k/edit?usp=sharing).

cc @a-kilroy

**Comment by kristinashu** [comment]
@a-kilroy I made some updates based on your feedback, let me know what you think! Also shared with Lucy to get her feedback.

**Comment by a-kilroy** [comment]
Closing the loop. Left comments in doc that we are currently discussing in slack.

**Comment by kristinashu** [comment]
I'm going to close this ticket and we can open a new one if anything else comes up.
