### ISSUE TITLE
Media files in S3 (CoSS staging)

### ISSUE THREAD

**Issue by johngian** [mozilla/coss#615]
We were having an issue with missing files after importing a DB dump from prod to stage (references to files where pointing to missing files). After manually syncing the 2 s3 buckets although files exist and bucket is public i am getting an access error.

As a workaround i added a bucket policy to make the bucket public.
@flamingspaz can you take a look why this happened and possibly remove the bucket policy ?

**Comment by akatsoulas** [comment]
This should be solved by now.
