### ISSUE TITLE
Wireframe for Resource detail page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#63]
Based on wireframes in #38 https://invis.io/72AN1X8WT#/221087690_Home

I will take a closer look at this page and iterate on it.

![planning resource detail 2x](https://cloud.githubusercontent.com/assets/1068783/23724318/1fb39c2a-0401-11e7-861b-984f07d0c7b3.jpg)

**Comment by jvallera** [comment]
Some key things to keep in mind in regard to resources:

1. They offer an easy way for community to contribute content (where contributing curriculum/activities is more complicated and involved). I currently help community leaders author and publish guides that reflect their local expertise. More [here](https://medium.com/read-write-participate/share-your-expertise-with-mozilla-clubs-around-the-world-936d1d94383f#.6hk2vm5zv) A variety of these are included on our guides [page](https://learning.mozilla.org/en-US/clubs/running) (specifically in the community generated content section at the bottom of the page). It would  be nice to have something like "submit a new resource" or "request a resource for something that currently missing" 

2. We have a guides and resources [archive](https://docs.google.com/a/mozilla.com/spreadsheets/d/1dpU02AiN2otBuN0W4Xt9cbIDMpBd3jKKLPs_1QsxeQo/edit?usp=sharing) and add new items to it regularly. Currently, I manually add links to the Django admin panel and can assign a category or language to them, which is great and easy to do. 

3. It would be great if these guides and resources were searchable, the same way activities will be searchable. Some of them are in different languages, which is important to highlight.

**Comment by comzeradd** [comment]
I'm closing wireframe issues, since we now have the style guide #214
