### ISSUE TITLE
Update OSSN logo to version with improved vertical spacing

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#653]
The OSSN logo has been updated to now have improved vertical spacing between the wordmark and the Mozilla logo. Please replace both the `primary-black` version and the `one-color-white` version with the attached SVGs. 

---
**Primary black and white**

![ossn-logo-bw.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/2d0755d1-05dd-49d7-a904-7118f43b313f)

All files also on [g-drive](https://drive.google.com/drive/folders/1xKRXXVNmvWk06eo7k0_5S4kc18Kxi3yg?usp=sharing).

[https://app.zenhub.com/files/80838213/f1ddc1bc-30d4-44a8-8079-bbcafab6b6a5/download](https://app.zenhub.com/files/80838213/f1ddc1bc-30d4-44a8-8079-bbcafab6b6a5/download)

**Comment by shikhar-scs** [comment]
@akatsoulas If anyone isnt working on the issue, can I please make the required changes?
