### ISSUE TITLE
Implement the basic landing page in Mezzanine

### ISSUE THREAD

**Issue by Pomax** [mozilla/coss#68]
Based on the work done in #98, implement the landing page as shown on https://redpen.io/gsccb3006ea4b5ee5a in Mezzanine:

![](https://s3.amazonaws.com/redpen-prod/red-pen-d417a040-de31-4d8d-c13d-1b7c27004474.jpg)

## Implementation status

- [ ] page header model
- [ ] clubs blolck model
- [ ] testimonial block
- [ ] signup block

- [ ] aggregated landing page model
- [ ] landing page template

- [ ] page header template fragment
- [ ] page footer template fragment

**Comment by a-kilroy** [comment]
Cross posting a comment from @Pomax "In order to prioritise projects with deadlines, some focus is shifting from "mezzanine as applicable to CoSS" (specifically, clubs) to "mezzanine as applicable to the Network site that's being built". with the booknote that this is a bias adjustment, not a full course change, so work will still happen for coss, it just takes a backseat to Network in the priority list." Based off this, we are updating this issue to Sprint 4.

**Comment by Pomax** [comment]
Basic implementation doc: the page itself can be separated into several functional blocks, some of which are base schema data for a "landing page" type, some of which are ForeignKeys into separate models for capturing the information that needs to be presented on the page but is more specific instances of independent models.

![thingakajigger 2](https://cloud.githubusercontent.com/assets/177243/24620449/9793680a-1852-11e7-9b0d-4f2a53599b02.jpg)

**Comment by Pomax** [comment]
building blocks based on implementation design:

- [ ] header
- [ ] page header block
- [ ] clubs block
- [ ] testimonial block
- [ ] signup block
- [ ] footer

### header

This can be a  written as a template fragment without a model backing

- logo image
- nav bar - built by tapping into mezzanine
- user block - *this has to wait until we have a viable login system*

### page header block

- title heading
- description
- in-page navigation link to sign-up block 

### clubs block

- title heading
- one to three "club summary" blocks based on club data, using:
  - the club's image
  - the club's name
  - the club's description
  - a (relative) link to that club's site URL

### testimonial block

- personal photo
- personal quote
- "who said it" name
- "who said it" location, but only country name

### signup block

- heading
- description
- "engagement action" block
  - input field placeholder
  - "do it" button label
  - "where to submit this field's data" URL (true submit unless JS loads on top to turn it into dynamic JS)
  - consent checkbox
  - consent description

### footer

This can be a  written as a template fragment without a model backing

- a whole bunch of engagement links
- mozilla logo
- moz description

**Comment by comzeradd** [comment]
@kristinashu @Pomax do we have the Zilla font in `woff/woff2` format, so I could use it for the headers? Otherwise I'll use Open Sans for now.

**Comment by kristinashu** [comment]
@comzeradd Zilla still isn't available yet (should be available any day now) so yes, please just use Open Sans or Fira for now.

**Comment by comzeradd** [comment]
This is no longer in scope. Landing page has been implemented in Wagtail.
