### ISSUE TITLE
Salesforce Email Capture

### ISSUE THREAD

**Issue by a-kilroy** [mozilla/coss#69]
Prototype Salesforce Email Capture in Mezzanine

**Comment by kristinashu** [comment]
On the design front, I've added it to the comp: https://redpen.io/qc3e404e3497a22e15

**Comment by alanmoo** [comment]
This is a regular POST request, so we don't need to worry about setting up a basket container unless we want to see what it looks like on the other end. We can just test making a simple AJAX call.

**Comment by a-kilroy** [comment]
Great! I'd love to have this as a widget that people can select which email capture to use. I have done this a few ways in the past so pretty open to how we do it.

**Comment by alanmoo** [comment]
Can you clarify what you mean by "people" and "which email capture to use"?

**Comment by a-kilroy** [comment]
People = admins/most likely staff
Which email capture to use = I expect that program staff will have several email lists they might want to pick from for a page (general, program specific, location specific, role specific, etc) and it would be ideal that they can self select that when setting up a new page. Does that help? Still confusing?

**Comment by alanmoo** [comment]
Closed by #108
