### ISSUE TITLE
Discuss localization 

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#71]
Localization the Clubs website will be important. Both for language and content. Few things to consider:
- how do we do this progressively/iteratively (entire website, pages at a time, sections at a time...)
- how do we get help translating text
- what tech do we use (eg Mezzanine, pontoon...)

This is fairly new to me so please add your thoughts @a-kilroy @Pomax @alanmoo

**Comment by Pomax** [comment]
for clubs using pontoon (itself a django project) in collaboration with mezzanine seems an approach that will let us ask others how they've already done this on the MoCo side. For individual clubs some of the localization will be in the hands of the clubs themselves (descriptions, lesson plans, etc. can all be written for their own locales, we don't need to insist on a master English version) and the UI we supply can be translated through pontoon string localization that we then pull in for serving the right text to the right people.

**Comment by kristinashu** [comment]
Pontoon does sounds like the way to go. 

One use case is the [resources page](https://learning.mozilla.org/en-US/clubs/running), you can see how currently, we have to list each resource in every available language. Once we have proper localization on our site, are we able to update those links to show only the relevant language?

**Comment by a-kilroy** [comment]
Additionally the admin is available in several languages. I suspect we'll keep the pontoon integration for a later sprint after we have some minimal product. Or did we want to build it in before then?

**Comment by kristinashu** [comment]
I was thinking we would add pontoon and the language picker to the landing page after it's built.

**Comment by a-kilroy** [comment]
cool. I think defaulting to earlier is a good best practice for us.
