### ISSUE TITLE
Update OI Challenges logo to version with improved vertical spacing

### ISSUE THREAD

**Issue by m-branson** [mozilla/coss#712]
The OI Challenges logo has been updated to now have improved vertical spacing between the wordmark and the Mozilla logo. Please replace both the `primary-black` version and the `one-color-white` version with the attached SVGs. 

---
**Primary black and white for visual reference**

![oic-logo-bw.png](https://images.zenhubusercontent.com/589c8c1a51aa2c305773eb6b/0e346863-39e5-4bb7-82be-839680dcf923)

All files also on [g-drive](https://drive.google.com/open?id=1INhUutknR8S1Fdk7UA8hO2frdosWtSE_).

SVGs for implementation: [https://app.zenhub.com/files/80838213/90e57b6f-12f8-4de5-9d8c-d2e807b684fd/download](https://app.zenhub.com/files/80838213/90e57b6f-12f8-4de5-9d8c-d2e807b684fd/download)

**Comment by divyabaid16** [comment]
I want to solve this issue. Can you please tell me that where can I find Open Innovation Challenge code?
That is, code referring to [Challenges](https://challenges.mozilla.community) ?
