### ISSUE TITLE
Wireframe for featuring people

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#89]
Something similar to current [Regional Coordinator page](https://learning.mozilla.org/en-US/clubs/coordinators) and possibly Club Captain [testimonials](https://learning.mozilla.org/en-US/clubs/start).

**Comment by kristinashu** [comment]
I'm noticing people like Andre have quite a few Mozilla profiles: 
https://learning.mozilla.org/en-US/clubs/coordinators 
https://mozillians.org/en-US/u/andregarzia/ 
https://reps.mozilla.org/u/andre/

I'd like to leverage all the IAM and mozillians.org work happening now and just have a thumbnail for people and then link to their profile on mozillians (rather than having them maintain several profiles).

We can feature people throughout the site with quotes and pic with link to their mozillian profile. Here are a few examples:

Quotes on the home page:
![home 2x](https://cloud.githubusercontent.com/assets/1068783/23916702/564580c0-08aa-11e7-82c5-39952cad194b.jpg)

Pic of CC with a link to their mozillian profile on event details page:
![event details 2x](https://cloud.githubusercontent.com/assets/1068783/23916707/5c90e3b6-08aa-11e7-8407-c9950d1c44ea.jpg)

Pic of CC + RC with a link to their mozillian profile on Club's details page:
![club details 2x](https://cloud.githubusercontent.com/assets/1068783/23917127/96bb4c4c-08ab-11e7-8b0c-e71c8c767f3a.jpg)

Quotes on the about page:
![about 2x](https://cloud.githubusercontent.com/assets/1068783/23916700/541fd96c-08aa-11e7-9d26-17d1322c0b3e.jpg)

We could also feature people within a resources, if an RC or CC helped make it...

Or we could be something as thorough as this (with thumbnails for everyone), but this seems too extensive:
![people copy 2x](https://cloud.githubusercontent.com/assets/1068783/23914670/e1f9e89c-08a3-11e7-9e63-7db05c04b657.jpg)

@a-kilroy @LucyeoH @bacharakis @jvallera @amirad let me know i you have any thoughts on this.

**Comment by a-kilroy** [comment]
Yes! This is a great use of CoSS 'glue'

**Comment by m-branson** [comment]
Nice @kristinashu ... appreciate that we're pushing people to Mozillians. 👍 

Question came to mind (apologies if it's too granular at this point?): When a user clicks on a CC/RC to view their profile, is it 'contact' that takes them to Mozillians or a different link (like their image)? Wondering if we can communicate to a user that they'd be leaving this site and going to another when they click the CC/RC...perhaps communication could happen via copy on an image hover?

**Comment by kristinashu** [comment]
Thanks for taking a look @m-branson! I was thinking the name and image would link to their profile. I'm never too sure what to do with external links. I don't like to use hovers for extra content because it won't work on touch devices. I have used an external link icon before but it sometimes looks very repetitive when there are a lot of links. I wondering if regular users would learn that profile links link out? Maybe something to test...

**Comment by m-branson** [comment]
Thanks for clarifying @kristinashu...name/image sound good for profile linking, and yeah, I too wonder if users would learn that those are external links?

Touch devices are absolutely important to keep in mind. How do you feel about designing interactions a little differently between desktop to touch: e.g. desktop gets an intuitive link hover state (overlay, underline, color change, etc) whereas touch devices could have a separate text link/button (view profile). This may help cut down on the repetition for desktop and keep touch as user friendly as possible? 

Testing would give us some good data to work with. 🥇

**Comment by kristinashu** [comment]
This ticket is good to close, we can work out the finer details at the design stage.
