### ISSUE TITLE
Discuss image upload criteria

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#90]
This will be a key need for the CMS. Let's discuss options and best case scenarios. 

Need to explore:
- how to prevent too low res and too high res images (tool tip, warning message...)
- how to crop image to a specif ratio and dimensions (tool tip, focus point with auto crop...)

For reference, @m-branson has created a [deck](https://docs.google.com/presentation/d/1wIFku0mq7OKj_BhpXJJV0q4z5lPn5YfsiulhxpzS7XA/edit?usp=sharing) with some great benchmarks from a user's perspective.

We will need to balance this with engineering perspective that we don't want to do too much customization. So let's also see what Mezzanine can do out of the box.

cc @a-kilroy @m-branson @Pomax @alanmoo @xmatthewx

**Comment by m-branson** [comment]
Thanks for populating this ticket and pointing to the deck @kristinashu (deck annotation will be done today).

As mentioned in our morning stand up: here is a focal point image resize tool that was built as a plugin for Craft, can be used as JS elsewhere. Provides a good visual reference of desired resize capabilities as well.

https://github.com/smcyr/Craft-FocusPoint
