### ISSUE TITLE
How to handle long pages

### ISSUE THREAD

**Issue by kristinashu** [mozilla/coss#94]
This is an ongoing design problem... We know people would rather scroll than click but at some point pages just get too long! This is bad for users with low-bandwidth and can become tough to navigate. Things that try to solve this, like tabs and accordions, are also troublesome (as @a-kilroy pointed out: less mobile friendly, less flexible for localization, not the best for screen readers...). Would having a sub nav (secondary menu) be better? @m-branson also mentioned https://guides.github.com/activities/hello-world/ but this isn't perfect either, disappears on mobile.

Let's do some research and solve this!

Example:
![club details 2x](https://cloud.githubusercontent.com/assets/1068783/24018445/19feabb6-0a51-11e7-82bc-36a194f4e004.jpg)

**Comment by m-branson** [comment]
Nice, thanks for making this a trackable ticket @kristinashu ... will populate some other ideas as yeah, githubs is flawed. ;)

**Comment by a-kilroy** [comment]
Do you want to tag team this research or should I assume one or both of you is handling? AKA do you want/need my help or is it redundant ?

**Comment by kristinashu** [comment]
Megan and I got it!

**Comment by m-branson** [comment]
Reference links that were talked through on Friday, plus a couple more examples from those sites...

**https://material.io/guidelines/**
- Classic and simple navigation menu that houses open/close sub menus.
- Within pages, content is condensed into accordion style sections. This works well, but could be better if:
  - The headings for the in page subsections differed from the h1
  - Included an icon that helped communicate that these expand
- This [Tabs](https://material.io/guidelines/components/tabs.html#tabs-types-of-tabs) section is good food for thought
- Use of [scrollable tabs](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQscHVOR1FVV2JjQms/components-tabs-typesoftabs_scrollable_tabs_01_xhdpi_003.mp4) is a great way to overview what content is 'hidden' and allow users to make educated decisions for continued exploration.
---
**http://www.apple.com/ipad/**
- This page (and most other category level pages of apple.com) utilize a sub menu to assist in user wayfinding
  - The sub menu features icons and labels (albeit labels are rather small)
  - A side scroll allows the sub menu to feature more than one screen width's worth of options
- Note the accordion style footer organization as well
- [Elsewhere on the site](http://www.apple.com/shop/iphone/iphone-accessories) users are given a drop down menu option to navigate further within a section.
---
**https://toolkit.mozilla.org/method/job-to-be-done/**
- This example is one of our own (thanks @kristinashu & @flukeout) 😄 
- It utilizes a drop down menu option that provides anchor links to an in page subsection.
- I appreciate this approach as it is a great baseline level user experience.

**Comment by a-kilroy** [comment]
Wow. Lots of great stuff here. From my perspective, I think the piece of content in the current wireframe that will help us pick a direction is the club title and location. The way it is currently mocked up is that it remains static while the other content is in different surfaceable sections. My first instinct is that I agree with this. I think keeping it static though creates a separation between the two navigation elements that feels at odds with the tabs menu in Material link and with the apple example. So I am wondering if we keep these elements static and that helps us make a directional choice or if we contemplate moving it into one of the sub tab sections so that the navs more closely resemble one of the other options. Or another option? Not the expert here so just giving my reaction.

**Comment by kristinashu** [comment]
Needs for this has shifted slightly (although I'm sure the need to solve for long pages will come up again eventually).

I approached the Club Detail page a little differently and was able remove the original problem so we no longer need tabs at all. 
![club details 2x](https://cloud.githubusercontent.com/assets/1068783/24516732/9094fe6c-1530-11e7-9812-1059ff3101e4.jpg)

But, we now have a more complex About page. This will need a secondary nav: for scalability (in the future, we might have a lot of different types of Clubs) and for shareability (unique urls), for accessibility (lower bandwidth), and probably some other type of "bility".

So we'll want to look at this through the secondary-nav lens rather than long-pages.

![about campus 2x](https://cloud.githubusercontent.com/assets/1068783/24516739/9747ad18-1530-11e7-955f-259c10eec8bb.jpg)
![about 2x](https://cloud.githubusercontent.com/assets/1068783/24516740/9766539e-1530-11e7-982e-be483adb479c.jpg)

**Comment by m-branson** [comment]
Thanks for noting the shift here @kristinashu (and the great reactions @a-kilroy).

I've taken learnings from this ticket and applied them on the IAM project as well, utilizing the OI Toolkit dropdown/anchor nav solution. This option feels most intuitive for use with large subsections of content. If we were looking at a build that was more 'classically tabbed' I may lean a bit more toward a Material inspired solution.

Closing this ticket.
